### ISSUE TITLE
v1.0 Todo List 项目计划

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin#172]
目前架子在重构中 #277 ，1.0 可能暂时不会发布，等全新的架子发布后再来完善Todo

**Comment by honghuangdc** [comment]
SoybeanAdmin 1.0发布后，后面进入维护阶段，新功能暂时不添加，作者后面会着重于开发一个基于UnoCss的UI库以及SoybeanJS团队的技术栈基建工作。

**Comment by baixjian** [comment]
感谢开源～，thin 版本会持续更新嘛

**Comment by honghuangdc** [comment]
> docker 好像拉不下来了？顺便想问下，tauri 分支和 go 后端分支还要人不 想帮忙写点

当然可以，欢迎来贡献！

**Comment by honghuangdc** [comment]
> 

会的，定期更新

**Comment by honghuangdc** [comment]
> 感谢开源～，thin 版本会持续更新嘛

当然会的

**Comment by 1046762075** [comment]
> * [ ]  [完善基于vite的vue路由插件，生成路由声明、导入和路由模块定义(ing...)] [https://github.com/soybeanjs/vite-plugin-vue-page-route](url)
> * [ ]  请求模块重构，抽离出单独一个库[https://github.com/soybeanjs/request](url)
> * [ ]  布局组件、Tab标签组件重构至 [https://github.com/soybeanjs/materials](url)
> * [ ]  国际化实现
> * [ ]  高级表格组件封装完善
> * [ ]  完善文档
> * [ ]  发布SoybeanAdmin 1.0

请问当下进度多少啦

**Comment by honghuangdc** [comment]
第一个插件已经实现了，还在测试，有些小问题需要修复

**Comment by 1046762075** [comment]
好的 谢谢


　　　　　　　汀西氟
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "honghuangdc/soybean-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月15日(星期天) 晚上7:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [honghuangdc/soybean-admin] Todo List 项目计划 (Issue #172)





 
第一个插件已经实现了，还在测试，有些小问题需要修复

**Comment by Wyatex** [comment]
期待1.0版本的发布，如果功能稳定之后我想和我的小伙伴们维护一个go的后端， 放到[MatrixAdminGoFrame](https://github.com/MatrixCross/MatrixAdminGoFrame)进行维护，要是感兴趣的也可以一起来维护

**Comment by honghuangdc** [comment]
> 期待1.0版本的发布，如果功能稳定之后我想和我的小伙伴们维护一个go的后端， 放到[MatrixAdminGoFrame](https://github.com/MatrixCross/MatrixAdminGoFrame)进行维护，要是感兴趣的也可以一起来维护

欢迎贡献 👍

**Comment by greper** [comment]
`高级表格组件封装完善`
这个可以试试我的fast-crud项目，需求高度匹配：https://github.com/fast-crud/fast-crud
我们这边小伙伴希望我出一下这款admin的starter，https://github.com/fast-crud/fast-crud/issues/82
我想，与其我集成一个，不如在官方demo上直接集成fast-crud，不知大佬是否看得上

**Comment by honghuangdc** [comment]
> `高级表格组件封装完善` 这个可以试试我的fast-crud项目，需求高度匹配：https://github.com/fast-crud/fast-crud 我们这边小伙伴希望我出一下这款admin的starter，[fast-crud/fast-crud#82](https://github.com/fast-crud/fast-crud/issues/82) 我想，与其我集成一个，不如在官方demo上直接集成fast-crud，不知大佬是否看得上

欢迎贡献，可以先在一个新分支上集成，我看看效果先 😄

**Comment by West121** [comment]
多页签这样设计是不是好一点？
![image](https://user-images.githubusercontent.com/29170680/221743410-547ce0c6-c081-4765-a25b-4e7c9e10b051.png)

**Comment by honghuangdc** [comment]
> 多页签这样设计是不是好一点？ ![image](https://user-images.githubusercontent.com/29170680/221743410-547ce0c6-c081-4765-a25b-4e7c9e10b051.png)

这个仁者见仁，智者见智，再说现在的有啥问题

**Comment by honghuangdc** [comment]
> > 多页签这样设计是不是好一点？ ![image](https://user-images.githubusercontent.com/29170680/221743410-547ce0c6-c081-4765-a25b-4e7c9e10b051.png)
> 
> 这个仁者见仁，智者见智，再说现在的有啥问题

如果也想实现这样的页签，可以提供多种选择，属于锦上添花，需求意愿不高，或许可以自己实现然后提PR

**Comment by honghuangdc** [comment]
> > > 多页签这样设计是不是好一点？ ![image](https://user-images.githubusercontent.com/29170680/221743410-547ce0c6-c081-4765-a25b-4e7c9e10b051.png)
> > 
> > 
> > 这个仁者见仁，智者见智，再说现在的有啥问题
> 
> 如果也想实现这样的页签，可以提供多种选择，属于锦上添花，需求意愿不高，或许可以自己实现然后提PR

排在2.0 #188

**Comment by linhaikun2019** [comment]
1.0版开发好了吗

**Comment by neozo** [comment]
1.0计划什么时候发布呢

**Comment by yjhenan** [comment]
移动端有计划适配下吗

**Comment by honghuangdc** [comment]
> 移动端有计划适配下吗

旧的布局组件有兼容移动端，新的没有兼容

**Comment by greper** [comment]
> > `高级表格组件封装完善` 这个可以试试我的fast-crud项目，需求高度匹配：https://github.com/fast-crud/fast-crud 我们这边小伙伴希望我出一下这款admin的starter，[fast-crud/fast-crud#82](https://github.com/fast-crud/fast-crud/issues/82) 我想，与其我集成一个，不如在官方demo上直接集成fast-crud，不知大佬是否看得上
> 
> 欢迎贡献，可以先在一个新分支上集成，我看看效果先 😄

最近有空在soybean上集成了一下fast-crud
demo链接:  http://fast-crud.docmirror.cn/soybean/crud/demo
效果还是不错的。

唯一的问题是 fast-crud要兼容多种底层ui，所以fast-crud使用到的naive组件需要全局注册。
https://github.com/fast-crud/fs-in-soybean-admin/blob/fs/src/plugins/fast-crud/naive.ts

**Comment by honghuangdc** [comment]
> > > `高级表格组件封装完善` 这个可以试试我的fast-crud项目，需求高度匹配：https://github.com/fast-crud/fast-crud 我们这边小伙伴希望我出一下这款admin的starter，[fast-crud/fast-crud#82](https://github.com/fast-crud/fast-crud/issues/82) 我想，与其我集成一个，不如在官方demo上直接集成fast-crud，不知大佬是否看得上
> > 
> > 
> > 欢迎贡献，可以先在一个新分支上集成，我看看效果先 😄
> 
> 最近有空在soybean上集成了一下fast-crud demo链接: http://fast-crud.docmirror.cn/soybean/#/crud/demo 效果还是不错的。
> 
> 唯一的问题是 fast-crud要兼容多种底层ui，所以fast-crud使用到的naive组件需要全局注册。 https://github.com/fast-crud/fs-in-soybean-admin/blob/fs/src/plugins/fast-crud/naive.ts

老哥，你提个PR

**Comment by greper** [comment]
提了😄，https://github.com/honghuangdc/soybean-admin/pull/227

**Comment by TokyoHot998** [comment]
![image](https://github.com/honghuangdc/soybean-admin/assets/20854221/8945b676-7690-48c5-8c9a-17746bb7f656)
mock打包导致 n-upload 组件拿不到 response

**Comment by honghuangdc** [comment]
> ![image](https://user-images.githubusercontent.com/20854221/238577695-8945b676-7690-48c5-8c9a-17746bb7f656.png) mock打包导致 n-upload 组件拿不到 response

已修复 9b19f96

**Comment by honghuangdc** [comment]
> > ![image](https://user-images.githubusercontent.com/20854221/238577695-8945b676-7690-48c5-8c9a-17746bb7f656.png) mock打包导致 n-upload 组件拿不到 response
> 
> 已修复 [9b19f96](https://github.com/honghuangdc/soybean-admin/commit/9b19f96ff63efa437f41d50089d9bb4f09645f91)

添加了开关 VITE_PROD_MOCK，如果不需要mock接口时，设置为N，就不会被mockjs影响XHR请求了

**Comment by kenixFog** [comment]
主题颜色这一块，有没有好的优化方案，根据暗亮主题，对主题颜色稍微进行优化，重新生成~~目前同一种颜色有时候不能完全适应暗亮主题，存在暗黑没问题，但是亮色刺眼，亮色没问题，暗黑又稍微有些看不清~~

**Comment by MrChildrenHY** [comment]
表格组件能否集成vxetable呢，兼容编辑表格使用naiveui各类输入组件

**Comment by mesak** [comment]
嵌套路由能實現一下嗎？

**Comment by chinaZoulx** [comment]
商业版计划多久出？

**Comment by Oscaner** [comment]
> SoybeanAdmin 1.0发布后，后面进入维护阶段，新功能暂时不添加，作者后面会着重于开发一个基于UnoCss的UI库以及SoybeanJS团队的技术栈基建工作。

Hi, honghuangdc.

我目前在计划做一个纯 TS 版本的后端管理框架。后端采用 TS + Express + JWT + MySQL 等技术，并遵循 [nodebestpractices](https://github.com/goldbergyoni/nodebestpractices) 最佳实践。

但是前端一直定不下来，很多 admin dashboard 处于断更的状态。
SoybeanAdmin 您会计划长期维护吗？目前的 v1.0-beta 是否可以采用？或者说是否可以一起协作？

这是我的 project [nodite-light](https://github.com/nodite/nodite-light)

**Comment by honghuangdc** [comment]
v1.0-beta.1 已发布 25fc24c，新的意向及需求将再后面的版本考虑逐渐实现

**Comment by honghuangdc** [comment]
> > 移动端有计划适配下吗
> 
> 旧的布局组件有兼容移动端，新的没有兼容

v1.0 的已经全面兼容移动端
