### ISSUE TITLE
v2.0 需求意向清单

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin#188]
目前架子在重构中 #277 ，所有的需求意向将在架子搭建完成后重新进行考量

- [ ] 锁屏组件
- [ ] 多场景的列表管理
- [ ] 侧边主菜单，顶部子菜单布局
- [ ] 集成iframe组件及缓存
- [ ] 路由插件支持路径参数、一个页面文件能生成多个路由
- [ ] 菜单数据从路由数据剥离，支持自定义菜单数据，然后在关联路由数据
- [ ] 页签支持单个拖动
- [ ] 解决循环依赖

**Comment by nodeds** [comment]
> * 主题效果.比如说到端午节,  中秋节,  设置提前(自定义)5天显示这端午节的主题风界面,  端午节过后, 自动恢复默认的主题, 可在首次进入首页的时候加一下 端午节动画效果等等或者也可以在登陆的页面同步这种节假日的动画特效, 参考链接 https://huke88.com/search/video?keyWorld=%E7%AB%AF%E5%8D%88%E8%8A%82&identify=1677502208
> * 关于系统管理的tabel应该是用的最多的, 用户管理 参考链接 https://lolicode.gitee.io/scui-doc/demo/#/setting/user
> * 抽屉组件
> * 地图组件 能否增加 一个数组集传入 经纬度   能显示多个用户, 多个商家, 多个供应商,的位置, 并分别与不同的颜色标注,和title 用于显示大数据的场景,
> * 穿竣俊 ,A卡片形式的列表里面的第一个商品和第三个商品,  我选择了后, 自动到右边的 卡片列表,
> * A卡片列表 与 B卡片列表 的 数据进行关联分组

**Comment by zgsgs** [comment]
- [ ] 添加 二次封装 Table 组件示例，支持配置生成， 复杂筛选框 [参考](https://vue-admin-beautiful.com/admin-plus/#/vab/table/comprehensiveTable)
- [ ] 新增 表单生成组件, 支持配置生成对应表单
- [ ] 新增 更多布局模式, 如分栏布局，综合布局等，详情可参考 [vue-admin-better](https://vue-admin-beautiful.com/admin-plus/#/index)
- [ ] 新增 Excel 在线编辑示例
- [ ] 新增 主题定制功能， 进一步可以打造主题市场（这个难度比较大，可以延后再搞）
- [ ] 新增 动画示例
- [ ] 新增 水印示例
- [ ] 新增 右键菜单示例
- [ ] 新增 引导动画示例
- [ ] 新增 三方登录对接示例
- [ ] 新增 WebSocket示例， 比如系统更新功能，在线客服，消息推送等
- [ ] 新增 Excel、Word、PDF预览示例
- [ ] 新增 ECharts 对接封装
- [ ] 新增 常用后台页面设计案例
- [ ] 支持 更高级的文本编辑器案例

以上只是列出可以做的功能点， 可以根据任务难易，重要程度等进一步讨论和划分。

**Comment by lauralxj** [comment]
可以做个常用的组织人员选择框，像icon图标选择一样但支持单选和多选，model 框左组织树，右人员图标姓名
这可以做成组件或示例吧

**Comment by honghuangdc** [comment]
> 

提的意向都太业务化了

**Comment by honghuangdc** [comment]
> 

1.高级表格在v1.0中会跟进实现
2.自动生成表单这个借用第三方的库，不考虑基于naiveUI来做
3.v2.0会新增一个侧边父菜单，顶部子菜单的布局，已经满足很多场景
4.依赖于第三方库，后面有群友可以自行实现然后提PR
5.更多的主题定制暂时不会考虑在naiveUI上实现
6.更多的插件示例让想为项目贡献的群友提PR

**Comment by honghuangdc** [comment]
> 可以做个常用的组织人员选择框，像icon图标选择一样但支持单选和多选，model 框左组织树，右人员图标姓名 这可以做成组件或示例吧

偏向业务化的需求暂时不考虑

**Comment by honghuangdc** [comment]
> 多页签支持拖动排序 (类似chrome页签)

目前的Tab页签是通过左右拖拽来进行滑动的，和页签的单个拖动冲突了，后面可以实现一个支持页签单个拖动但是整体不是通过拖拽左右滑动的T页签

**Comment by lwx7832** [comment]
考虑适配移动端吗

**Comment by Kchengz** [comment]
> > 
> 
> 1.高级表格在v1.0中会跟进实现 2.自动生成表单这个借用第三方的库，不考虑基于naiveUI来做 3.v2.0会新增一个侧边父菜单，顶部子菜单的布局，已经满足很多场景 4.依赖于第三方库，后面有群友可以自行实现然后提PR 5.更多的主题定制暂时不会考虑在naiveUI上实现 6.更多的插件示例让想为项目贡献的群友提PR

您好，我是[KDesigner设计器](https://github.com/Kchengz/k-designer)的作者，我想将KDesigner集成到这个项目，利用KDesigner设计器中k-builder组件编写配置式表单组件后像您这边提交pr
通过编写json schemas生成表单
默认提供naiveUI基础表单组件
可扩展组件表单
也可通过插槽插入

k-designer也可以作为一个页面或者表单设计器，直接进行拖拽设计（目前设计不够完善，后面会持续更新）
完全之后也会编写相应文档，不知道能否参与进来

**Comment by lloydzhou** [comment]
后台依赖的echarts组件建议使用
https://github.com/ecomfe/vue-echarts
或者
https://github.com/lloydzhou/vuecharts

**Comment by JanYork** [comment]
适配移动端，或者来个小程序，针对及时性较强的后台管理需求

**Comment by qiuquanwu** [comment]
真的搞笑，搞了新版，把以前的依赖全部搞烂掉了eslint-config-soybeanjs-vue

**Comment by MetSystem** [comment]
动态路由

**Comment by ahualy** [comment]
有没有相对应的java后端，我想把前端左侧的菜单基于后端实现的

**Comment by baixjian** [comment]
有考虑fork项目改成ant-deign-vue的ui ，不知道难度大不大

**Comment by ArtisanQ** [comment]
可以参考umi或者fes.js, 将权限，路由，请求，布局做成插件形式引入嘛

**Comment by fanslead** [comment]
页面生成器能不能搞一个

**Comment by layxyer** [comment]
可以支持顶部菜单+左侧菜单吗,顶部菜单显示一级菜单,左侧菜单显示选中的顶部一级菜单下的菜单

**Comment by ashuicoder** [comment]
自动生成表单库推荐一下我开发的[naive-ui-form](https://ashuicoder.github.io/naive-ui-components/naive-ui-form.html)

**Comment by lwl504** [comment]
- [ ] 添加页面组件大小全局配置：如可选择大、中、小三种模式。

- [ ] 当页面出现滚动条时，添加回到顶部功能。

**Comment by Azir-11** [comment]
> * [ ]  添加页面组件大小全局配置：如可选择大、中、小三种模式。
> * [ ]  当页面出现滚动条时，添加回到顶部功能。

组件大小这个东西naive还不支持统一配置哦

滚动回顶部的这个东西的话.....对某些展示信息的页面貌似不太友好，容易遮挡，做的话还要考虑到单独配置不需要的页面，如果需要的人多的话可以加一个可配置开启的

**Comment by honghuangdc** [comment]
合并至 #364

**Comment by QQ755816** [comment]
table的行拖拽排序怎么实现

**Comment by Azir-11** [comment]
> table的行拖拽排序怎么实现

请不要此issue内提及无关问题
