### ISSUE TITLE
SoybeanAdmin 重构

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin#277]
SoybeanAdmin 将会进行重构，目前的版本将会低频地进行更新，新版 SoybeanAdmin 介绍如下：
1. 基于 Vue 3.3 + Vite 4 + TypeScript + UnoCSS 技术栈，支持Ant Design Vue v4、NaiveUI、ElementPlus
2. 基于 pnpm 的 monorepo
3. 国际化
4. 基于 [ElegantRouter](https://github.com/soybeanjs/elegant-router) 构建的路由系统，支持前端静态和后端动态路由两种模式
5. 提供基于axios和ofetch的请求封装
6. 系统主题定制私有化
7. 基于Apifox的在线Mock服务
8. 代码写法遵循 SoybeanJS 规范(待给出规范文档)

路线：
1. 核心架子，公共的菜单、头部和主题抽屉由自定义组件实现，与UI框架无捆绑
2. 核心架子文档
3. 代码开源
4. 接入 NaiveUI、AntDesignVue、ElementPlus
5. 接入不同UI框架的文档
6. 开源接入NaiveUI框架的源码

**Comment by honghuangdc** [comment]
由于开源项目的艰辛，重构后的 SoybeanAdmin 仍然会开源，不过开源协议会采取 GPL 协议，非商用免费，商用需要授权。

**Comment by wyhPro** [comment]
重构了那用现在版本的代码是不是得大改了0.0

**Comment by sincely** [comment]
感谢楼主,开源项目的艰辛深有体会!重构该版本同时,能提供js版本吗?不是人人都会使用typescript! 技术栈还是Vue 3.3 + Vite 4 + Tjavscript+ UnoCSS

**Comment by honghuangdc** [comment]
> 重构了那用现在版本的代码是不是得大改了0.0

现有的代码不会去变更，而是从0到1重新开发

**Comment by honghuangdc** [comment]
> 感谢楼主,开源项目的艰辛深有体会!重构该版本同时,能提供js版本吗?不是人人都会使用typescript! 技术栈还是Vue 3.3 + Vite 4 + javaScript+ UnoCSS

项目很多地方都需要借助TS的能力，还是有机会自己多学学TS

**Comment by wyhPro** [comment]
文档打不开了

**Comment by honghuangdc** [comment]
> 文档打不开了
> 

已经更换了新的地址 https://admin-docs.soybeanjs.cn/

**Comment by ques666** [comment]
SoybeanAdmin页面风格是真的很棒。不过二开入门学习成本有点高，似乎有一些自动生成的工具，但是没有说明生成代码的范围，显得不是很可控，或许文档可以更完善一点。

**Comment by Guyu23** [comment]
确实是比较现代的项目了，风格也不错，动画衔接做得也很好。那个侧栏收窄的动画挺有意思的，昨天刚在公司项目做了类似的效果，不过我司用的是 jQuery，实现的比较丑陋哈哈

**Comment by JiangNaa** [comment]
请问未来v1.0的NaiveUI 版本也是需要商业授权的吗？

**Comment by gaojiangtao-git** [comment]
请问下重构之后NaiveUI 版本  是收费的么

**Comment by honghuangdc** [comment]
> 请问下重构之后NaiveUI 版本 是收费的么

README里面写的很清楚了

**Comment by honghuangdc** [comment]
> 请问下重构之后NaiveUI 版本 是收费的么

README里面写的很清楚了

**Comment by knight-peter** [comment]
请问重构后的版本预计什么时候发布？

**Comment by honghuangdc** [comment]
> 请问重构后的版本预计什么时候发布？

12月份左右

**Comment by firmianaQ** [comment]
现在版本的路由可以使用@elegant-router/vue吗

**Comment by dodu2014** [comment]
1.0 beta 跑不起来，对node和npm版本有要求吗？

**Comment by lzb-libra** [comment]
希望老版的文档不要删除

**Comment by yyqxjwxy** [comment]
1.0 版本跳票了吗

**Comment by Azir-11** [comment]
> 1.0 版本跳票了吗

1.0目前已经基本完成，可以体验使用了

**Comment by yyqxjwxy** [comment]
> > 1.0 版本跳票了吗
> 
> 
> 
> 1.0目前已经基本完成，可以体验使用了

但是还没有正式发布对吧

**Comment by Azir-11** [comment]
> > > 1.0 版本跳票了吗
> > 
> > 
> > 1.0目前已经基本完成，可以体验使用了
> 
> 但是还没有正式发布对吧

是的

**Comment by yyqxjwxy** [comment]
> > > > 1.0 版本跳票了吗
> > > 
> > > 
> > > 1.0目前已经基本完成，可以体验使用了
> > 
> > 
> > 但是还没有正式发布对吧
> 
> 是的

什么时候正式发布呢

**Comment by Azir-11** [comment]
> > > > > 1.0 版本跳票了吗
> > > > 
> > > > 
> > > > 1.0目前已经基本完成，可以体验使用了
> > > 
> > > 
> > > 但是还没有正式发布对吧
> > 
> > 
> > 是的
> 
> 什么时候正式发布呢

代码已经完成了，现已切换至main分支，文档还在编写中，可以clone使用了，有疑问或者建议欢迎提issues

**Comment by honghuangdc** [comment]
> 你好 请问新版本现在发出了吗？

还没正式，重构后的代码已经在main分支，可以使用了

**Comment by CherishMvp** [comment]
> > 你好 请问新版本现在发出了吗？
> 
> 还没正式，重构后的代码已经在main分支，可以使用了

似乎权限管理部分无内容，等待更新还是？

**Comment by Azir-11** [comment]
> 我将项目clone下来，安装依赖后运行，给我一种感觉就是没有以前用起来丝滑了，有一个明显的地方就是右上角点击后弹出的菜单有个“个人中心”和“退出登录”这两个选项，当我第一次点击时，退出登录的图标显示的就特别慢。还有一个就是我非常喜欢老版本右上角那个搜索菜单的功能，希望作者能在百忙之中辛苦加一下。

菜单搜索会加上的，图标加载慢的原因可能和你的网络有关，你或许可以保存到本地或者使用CDN等内容让他的加载速度变快

**Comment by beijibeijing** [comment]
文档预计什么时候完成，1.0预计什么时候正式发布啊？期待~

**Comment by Azir-11** [comment]
文档正在编写，预计下个月应该差不多了

**Comment by honghuangdc** [comment]
> 文档预计什么时候完成，1.0预计什么时候正式发布啊？期待~

文档已发布 docs.soybeanjs.cn

**Comment by zhanglinweigithub** [comment]
请问项目中如何剥离路由生成插件，感觉在还多地方都依赖了这个插件。非常喜欢SobeanAdmin，但是路由生成插件用不明白，还是希望可以手动控制路由。大佬可以简单说一下如何从项目剥离这个插件吗

**Comment by honghuangdc** [comment]
> 请问项目中如何剥离路由生成插件，感觉在还多地方都依赖了这个插件。非常喜欢SobeanAdmin，但是路由生成插件用不明白，还是希望可以手动控制路由。大佬可以简单说一下如何从项目剥离这个插件吗
> 
> 

去看一下ElegantRouter的文档

**Comment by xiaochanghai** [comment]
现在犹豫使用NaiveUI还是新构建的版本呢，我看新构建的版本有段时间没有维护了

**Comment by Azir-11** [comment]
> 现在犹豫使用NaiveUI还是新构建的版本呢，我看新构建的版本有段时间没有维护了

新构建的版本有antdv和naive，两个都有持续的维护的

**Comment by honghuangdc** [comment]
已正式发布 v1.0.beta.1 ，等这个版本稳定个几天，就正式 release v1.0
