### ISSUE TITLE
1.0 版本替換 API 路徑

### ISSUE THREAD

**Issue by KenDev099** [soybeanjs/soybean-admin#314]
Hi

Fork main 分支的 1.0 版本後，想請問如何替換 API 路徑 ？

更改如下：

> env.config.ts > dev 環境下的 baseURL 替換成自己的 API 路徑
> .env.development > VITE_HTTP_PROXY=F

發現如下：

> 打開瀏覽器 F12 觀察 API 發送，要求 URL 路徑是正確的，但是會連續執行 2次 options 跟 2次 api，並且回傳 204
> 畫面上會連續跳出 4 個 Network Error 的 message。
> service/request/index.ts 裡的 createFlatRequest 的 onError 也會執行 4 次

看了很久還是找不出原因，我的 API 本身應該沒問題。舊專案跟 Postman 都是正常回傳

希望能幫忙看一下，感謝

**Comment by honghuangdc** [comment]
1.你关闭了本地代理，得你后端接口已经配置了代理
2.项目里面有完好的接口，有问题自己多排查自己的后端接口，postman调用接口和在浏览器调用接口本身就是两套环境，不能等同
