### ISSUE TITLE
如何搭建一个共享的 api typings 项目以实现多项目引用

### ISSUE THREAD

**Issue by dodu2014** [soybeanjs/soybean-admin#318]
1.0 后的项目架构很优秀，我还有1个移动端的项目，想共用一套 `typings`，类似你在 `packages `下的项目，例如 `@sa/ApiTypings`，能否实现一套api端的类型库，该怎么做，请大神指教

**Comment by honghuangdc** [comment]
移动端的项目代码和当前项目的代码不在同一个代码库里面？

**Comment by honghuangdc** [comment]
在同一个代码库就直接使用就行，需要保证 tsconfig.json 的 include 包含 packages。
如果不在同一个代码库，则通过发布第三包的形式，然后将包引入到 tsconfig.json 的 types 里面，参考现有的 naive-ui/volar

**Comment by dodu2014** [comment]
不再一个代码库，一个后端，两个前端项目，不想创建两套 api 的 typings

**Comment by dodu2014** [comment]
@honghuangdc naive-ui/volar 是这个吗？
https://github.com/tusen-ai/naive-ui/blob/main/volar.d.ts

还是有单独的项目？

**Comment by Azir-11** [comment]
自己发布一个提供type的包，类似你发的这个volar.d.ts，然后在tsconfig.json里包含进去，就像现有的这个naive-ui/volar一样
```
"types": ["vite/client", "node", "unplugin-icons/types/vue", "naive-ui/volar","your-api-typings"],
```

**Comment by Azir-11** [comment]
> naïve-ui/volar 是这个吗？ https://github.com/tusen-ai/naive-ui/blob/main/volar.d.ts
> 
> 还是有单独的项目？

新的包是单独的

**Comment by dodu2014** [comment]
好的 谢谢两位 @honghuangdc @Azir-11 ，我尝试做一下

**Comment by dodu2014** [comment]
![image](https://github.com/soybeanjs/soybean-admin/assets/15245544/dc39436e-0689-4e7a-8d7b-1fb8df248e7e)
![image](https://github.com/soybeanjs/soybean-admin/assets/15245544/cef13fad-f6f8-4dad-b7f7-cfa6698d3796)
![image](https://github.com/soybeanjs/soybean-admin/assets/15245544/2f931b52-dd9a-4af4-80ee-f760cec1d94b)

如图所示，我把所有api端的类型定义，转移到了单独的包中，该包并未发布到npm，在app项目中暂时使用路径引入类型，vscode在使用中，可以正常感知和使用，但tsconfig第一行报错，提示 `找不到“@tnt/webapi-types”的类型定义文件。` 
虽然不影响正常使用，但还是想把这个错误提示解决掉，该怎么做？

@honghuangdc @Azir-11

**Comment by Azir-11** [comment]
字面意思啊，types里面的路径其实是缩写，省略了最后的.d.ts，比如`vite/client`应该是到vite这个包下找`client.d.ts`，按照你写的这个路径，它没找到对应的.d.ts类型文件，不就报错了

**Comment by dodu2014** [comment]
👍👍@Azir-11 ，非常感谢。❤️❤️
admin 项目不需要引用就能用，发布到npm后，移动端项目引用也正常了。。。
