### ISSUE TITLE
R_ADMIN與R_SUPER是否是同樣的權限？

### ISSUE THREAD

**Issue by s414june** [soybeanjs/soybean-admin#320]
src/router/elegant/routes.ts中，
`roles: ['R_ADMIN']`
是否為誤植？

在導航守衛中我只有看到
`const SUPER_ADMIN = 'R_SUPER';`
這樣的判斷
或是說R_ADMIN是另一種權限？
（但我對於R_的意思感到困惑，不知道除了super的R還有其他字義？）
請協助解惑，謝謝～

另外，要不要增加不同權限的mock供權限模擬呢？

**Comment by honghuangdc** [comment]
这里的R_SUPER的目的是为了方便前端模拟前端的超级管理员权限

**Comment by s414june** [comment]
@honghuangdc  感謝回覆
其實我只是想確認R_ADMIN是什麼意思而已XD
大致明白，意思應該是`roles: ['R_ADMIN']`只是範例數據(管理員階級)，暫無應用到
R_SUPER即不用寫在roles裡面也可以查看所有顯示頁面者

@Azir-11 明白，是想說可以做不同登入狀態下選單篩選的示例(超級管理員/管理員/編輯者/查看者......)
例如在菜單管理>編輯中，也沒有角色權限可供多選(應要從角色編碼去對應角色名稱)，會覺得UI少了些什麼。建議可以添加
