### ISSUE TITLE
Please add soybean admin - primevue (unstyled) version

### ISSUE THREAD

**Issue by adiramardiani** [soybeanjs/soybean-admin#321]
Soybean currently has ant-design and naive-ui versions

I know you worked hard to maintain this theme, documentation, and language up to version 1, but I really hope there will be an unstyled Primevue based template version, I think it would be a good combination if Primevue had a template with menu navigation, history tabs, and dropdowns breadcrumbs like this theme ❤️ 

@honghuangdc

**Comment by Azir-11** [comment]
> Soybean 目前有 ant-design 和 naïve-ui 版本
> 
> 我知道您努力将这个主题、文档和语言维护到版本 1，但我真的希望会有一个基于 Primevue 的无样式模板版本，我认为如果 Primevue 有一个带有菜单导航、历史选项卡和像这个主题❤️这样的下拉面包屑的模板，那将是一个很好的组合
> 
> @honghuangdc

Thank you for your support of soybean. We do not have a large number of maintainers, so we may attempt this content at some point in the future. Contributions are always welcome, and we encourage you to implement your ideas on a new branch, just like what we did with fast-crud.

**Comment by honghuangdc** [comment]
After much deliberation, the version will not be planned later on。
