### ISSUE TITLE
动态路由信息接口数据如何根据菜单数据生成

### ISSUE THREAD

**Issue by jarryxy** [soybeanjs/soybean-admin#322]
![image](https://github.com/soybeanjs/soybean-admin/assets/56039867/83ff40d1-93ea-47a3-beb2-6ad60d99b0b0)

component是怎么生成的，菜单中没有这个配置

**Comment by honghuangdc** [comment]
组件这个属性还没加上
实现原理：
一级路由的component是由 布局组件和页面组件
多级路由的第一层是布局组件，子级路由的component是页面组件

**Comment by jarryxy** [comment]
ok 我自己完善一下
