### ISSUE TITLE
关于隐藏菜单问题

### ISSUE THREAD

**Issue by zuihou** [soybeanjs/soybean-admin#325]
问题： 路由配置时， 如何设置某个菜单的子菜单全部是隐藏菜单？

描述： 
```
消息中心       （1级菜单）
├── 消息管理   （2级菜单）
│   ├── 发布消息   （3级隐藏菜单）
│   ├── 查看消息消息 （3级隐藏菜单）
```

代码结构
```
views        
├── msgcenter
│   ├── msg
│    │   ├── index.vue
│    │   ├── msgview
│    │    │   ├── index.vue
│    │   ├── msgedit
│    │    │   ├── index.vue
│   ├── template
```

目前效果
<img width="692" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/8500410/2a53c2d5-969e-48c6-ac3d-23e2df54dffc">

如上图所示， “消息管理” 下级显示了2个菜单， 我希望：
1. 点击 “消息管理”  进入 `views/msgcenter/msg/index.vue` 
2. “发布消息” 和  “查看消息”   菜单隐藏起来，不在左侧菜单显示出来
3. 在任意页面，点击 “发布消息”  按钮，跳转到 `views/msgcenter/msg/msgview/index.vue` 
4. 在任意页面，点击 “查看消息”  按钮，跳转到  `views/msgcenter/msg/msgedit/index.vue`  
5. 左侧菜单能正常显示 消息中心和消息管理，且消息管理能点击后跳转到 步骤1 中的地址。 

自己做过的一些尝试：
1.  “发布消息” 和  “查看消息”   加了hideInMenu： true后，程序会按照这个方式显示。“消息管理” 无法点击
<img width="295" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/8500410/4cc106d7-8103-4e0a-aed4-3b846ef77263">

**Comment by zuihou** [comment]
vben 这个项目，有一个`hideChildrenInMenu` 参数能解决上述问题，不知道此框架能否解决

**Comment by zuihou** [comment]
文件树中msgview与msgedit不应在msg之内可以调整，但在业务上： 


消息管理是一个大功能，而发布消息、编辑消息、查看消息是 隶属于 消息管理的， 
<img width="1531" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/8500410/9f841bd0-0da3-4bb3-a4df-dafa62d4e30e">

在权限隶属关系上来讲，当我给用户分配  发布消息 编辑消息、查看 时， 一定是需要分配先分配 消息管理的。
<img width="399" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/8500410/f9c54d1b-6a55-4422-8084-543ce12e8a31">


假设现在我按照你的设计理念，将 消息管理、发布消息、编辑消息、查看消息 都平级存放了，我在分配权限时，就无法从隶属关系上进行控制， 管理员就可以只给用户分配 ”编辑消息“ 、”查看消息 “，而不分配” 消息管理“ 。 
但你连消息管理菜单都没有，光有 ”编辑消息“ 功能，怎么编辑数据呢？

**Comment by zuihou** [comment]
技术栈的设计都应该解决业务问题的，对于上述问题， 我有没有办法能修改你的源码来实现呢？

大概需要修改那些页面能给个提示吗

**Comment by honghuangdc** [comment]
首先系统的路由是基于 [Elegant Router](https://github.com/soybeanjs/elegant-router), 不支持这种路由
<img width="1168" alt="截屏2024-02-23 21 24 48" src="https://github.com/soybeanjs/soybean-admin/assets/49704545/2a20f51f-e159-4636-ab4c-3f0a74a2036c">

其次按照菜单的设计分为 目录、菜单和按钮
目录下面可以为菜单，而菜单就是最后一级了，不存在菜单下面还有菜单

**Comment by CYi1113** [comment]
> [vben](https://doc.vvbin.cn/guide/router.html#meta-%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E) 这个项目，有一个`hideChildrenInMenu` 参数能解决上述问题，不知道此框架能否解决

我这边也遇到了同样的问题，请问你这边目前解决了吗？

**Comment by honghuangdc** [comment]
https://soybeanjs.cn/function/hide-child/one 参照这个菜单
