### ISSUE TITLE
多菜单使用同一个路由时如何打开多个tab

### ISSUE THREAD

**Issue by MartinLongYW** [soybeanjs/soybean-admin#326]
背景：我做了一个通用的CURD页面，这个页面根据路由参数，加载不同的数据。多个菜单会使用该页面。
问题：现在点击菜单时，只能打开一个tab。
期望：点击不同菜单时，打开新tab。

**Comment by Azir-11** [comment]
目前tab新增的逻辑是`watch->route.fullPath`，所以只需要不同的`fullPath`就可以了，参考`https://soybeanjs.cn/function/tab`里的`
添加多标签页`

**Comment by MartinLongYW** [comment]
> 目前tab新增的逻辑是`watch->route.fullPath`，所以只需要不同的`fullPath`就可以了，参考`https://soybeanjs.cn/function/tab`里的` 添加多标签页`

是否我在 后端返回的菜单中，添加一个fullPath属性即可，如 /curd/list?a=1    /curd/list?a=2 。

**Comment by Azir-11** [comment]
> > 目前tab新增的逻辑是`watch->route.fullPath`，所以只需要不同的`fullPath`就可以了，参考`https://soybeanjs.cn/function/tab`里的` 添加多标签页`
> 
> 是否我在 后端返回的菜单中，添加一个fullPath属性即可，如 /curd/list?a=1 /curd/list?a=2 。
> 
> 试了下，菜单添加 fullPath: "/curd/list?pid=391744991924293" 属性，点击菜单的时候，还是不会添加新tab。找到watch->route.fullPath这个函数，发现fullPath还是/curd/list，后面的参数是缺少的。有不是有的地方把fullPath=path了

不用手动添加route.fullPath，正常情况下它应该带有参数，请确认跳转方式与示例是否相同，还是不行的话希望可以提供一个最小复现方法，比较麻烦的话也可以进QQ交流群，发我远程看看

**Comment by honghuangdc** [comment]
参照页面 系统功能 => 标签页，里面有一个页面打开多个Tab的示例

1. 配置菜单 meta 的属性 multi 为 true
2. 默认一个路由 path 对应一个 tab，当 multi 为 true时，如果有不同的 query 参数，会变成多 个tab
