### ISSUE TITLE
登录整体删除后，在新加登录文件，会产生在bases-layouts内，应该是路由自动生成那没考虑这个

### ISSUE THREAD

**Issue by Wrong2014** [soybeanjs/soybean-admin#330]
RT

**Comment by honghuangdc** [comment]
新生成的路由数据默认的布局会采用 layouts里面的第一个布局(目前是base)，然后可以自行更改路由数据的布局

**Comment by honghuangdc** [comment]
具体哪个页面需要哪种布局这个插件又没法知道，所以只能默认提供一个布局，再自行更改

**Comment by Wrong2014** [comment]
感谢你的回复，你说的我已经理解，也很中肯，一般确实是需要这么处理，只是可能我想表达的没有说太清楚，因为这里可能是误删除，我如果是同名（或者撤销删除）恢复应该遵循还原（退回）原则
