### ISSUE TITLE
run dev成功后页面无法显示

### ISSUE THREAD

**Issue by Kyrie1020** [soybeanjs/soybean-admin#332]
![image](https://github.com/soybeanjs/soybean-admin/assets/47716868/fb4a2249-feaf-40f8-8973-c238e4f77116)

![image](https://github.com/soybeanjs/soybean-admin/assets/47716868/7a4eb8ae-3bd0-48a9-b0c1-409f0d3537a8)

**Comment by Kyrie1020** [comment]
node:18.18.0
pnpm: 8.15.4

**Comment by honghuangdc** [comment]
端口有问题，默认的9527杀掉重新试试

lsof -i:9527
kill -9 [pid]
