### ISSUE TITLE
关于路由的layout使用的组件

### ISSUE THREAD

**Issue by Li-0221** [soybeanjs/soybean-admin#338]
作者您好，我在看本项目的生成路由方面有一个疑问。

我发现删除`router/elegant`文件夹，重新运行项目，生成的`router/elegant/routes.ts`与之前的不一样。

疑问1: 下图的这些差异是否时在生成`router/elegant/routes.ts`之后手动更改了部分内容？

疑问2: 页面使用的layout是否也是在`router/elegant/routes.ts`生成之后手动修改的？有没有其他方法指定页面的layout？

![image](https://github.com/soybeanjs/soybean-admin/assets/75083207/1ede8d03-da75-43b3-af1d-e30a5e075a85)

**Comment by honghuangdc** [comment]
是的，都是在生成后手动更改的，至于说为啥删掉之后重新生成的路由数据不一样，这个是因为修改后的路由数据都被删掉了，所以只能重新生成默认的，需要变更自行再修改。修改后再生成，是会进行数据对比的。
看一下插件的文档先理解一下 [Elegant Router](https://github.com/soybeanjs/elegant-router)
该插件是为了将手动配置路由的过程自动化，而不是向市面上的基于文件系统的路由插件那样
