### ISSUE TITLE
剥离路由生成插件

### ISSUE THREAD

**Issue by zhanglinweigithub** [soybeanjs/soybean-admin#340]
请问项目中如何剥离路由生成插件，感觉在还多地方都依赖了这个插件。非常喜欢SobeanAdmin，但是路由生成插件用不明白，还是希望可以手动控制路由。大佬可以简单说一下如何从项目剥离这个插件吗

**Comment by Azir-11** [comment]
去除插件，自行写出路由，导入vue-router中，其他地方大多都是读取meta的内容，运行起来有问题的地方再做修改就行了

**Comment by zhanglinweigithub** [comment]
今天尝试了一波，插件卸载之后框框报错，改了好多文件还是G，大佬能给出涉及的文件吗。走投无路了才来提issues求助

**Comment by Azir-11** [comment]
还没有尝试过，可能暂时没有办法给出，建议跟着报错一步步找原因并修改，如果没有必须的必要性，可以试着学一下插件的使用，对插件的使用有疑问的话可以随时询问

**Comment by zhanglinweigithub** [comment]
好的，我在研究研究
