### ISSUE TITLE
本地启动，F5刷新页面时，主题模式丢失数据

### ISSUE THREAD

**Issue by zuihou** [soybeanjs/soybean-admin#341]
最新main分支代码， 本地启动，F5刷新页面时，主题模式和主题配置  会丢失数据。

<img width="395" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/8500410/85e776c6-aba7-4187-8df4-b95991dc7608">

生产环境没有此问题。

**Comment by Azir-11** [comment]
开发模式下优先听本地的，通过更新 `src/theme/settings.ts` 中的 `themeSettings` 来更新主题设置，详情请看`initThemeSettings`
