### ISSUE TITLE
关于window.$message

### ISSUE THREAD

**Issue by zuihou** [soybeanjs/soybean-admin#344]
在F5刷新页面时， 页面还在下图的加载过程时， 若通过axisos调用后端接口，此时接口报错希望给与一些提示，
无论调用 `window.$message`、`window.$notification`、`window.$dialog` 、`useDialog()`、`useMessage()` 都是null，无法给与消息提示。

<img width="642" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/8500410/b53a9b5e-47d9-4c6a-b3e7-255f63d00ea9">

如图：
<img width="623" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/8500410/aab30100-0892-43db-81cd-cb77a6ec13ab">

请问有什么解决办法吗？

**Comment by Azir-11** [comment]
这个时候app.mount都没有执行，内容都还没挂载到页面上，肯定没办法给你显示出来的，你这个问题的场景是什么？一定要在挂载app之前调用吗？

**Comment by honghuangdc** [comment]
可以做一个函数的延迟执行，等到App挂载完后再执行这个错误提示
具体方案：
1. 判断$message实例是否存在
2. 不存在的情况下，将错误提示放进一个函数内，再把函数推到一个待执行栈中
3. 监听实例是否发生变化，变化后存在的情况下依次执行待执行栈中的函数

**Comment by Azir-11** [comment]
> 可以做一个函数的延迟执行，等到App挂载完后再执行这个错误提示 具体方案：
> 
> 1. 判断$message实例是否存在
> 2. 不存在的情况下，将错误提示放进一个函数内，再把函数推到一个待执行栈中
> 3. 监听实例是否发生变化，变化后存在的情况下依次执行待执行栈中的函数

好一个事件循环哈哈哈哈哈

**Comment by zuihou** [comment]
> 这个时候app.mount不一定有执行，内容都还没挂载到页面上，肯定没办法给你显示出来的，你这个问题的场景是什么？一定要在挂载app之前调用吗？

刷新页面时， initDynamicAuthRoute 方法获取后端的路由数据， 此时后端接口报错，需要给与提示

**Comment by zuihou** [comment]
> 可以做一个函数的延迟执行，等到App挂载完后再执行这个错误提示 具体方案：
> 
> 1. 判断$message实例是否存在
> 2. 不存在的情况下，将错误提示放进一个函数内，再把函数推到一个待执行栈中
> 3. 监听实例是否发生变化，变化后存在的情况下依次执行待执行栈中的函数

听着就晕， 大佬，有无计划加一个功能？ 上面提到的场景，需求确实是存在的呢。

**Comment by Azir-11** [comment]
> > 可以做一个函数的延迟执行，等到App挂载完后再执行这个错误提示 具体方案：
> > 
> > 1. 判断$message实例是否存在
> > 2. 不存在的情况下，将错误提示放进一个函数内，再把函数推到一个待执行栈中
> > 3. 监听实例是否发生变化，变化后存在的情况下依次执行待执行栈中的函数
> 
> 听着就晕， 大佬，有无计划加一个功能？ 上面提到的场景，需求确实是存在的呢。

简单点的方案就写个倒计时定时器，定个几百毫秒延时执行，每次执行判断$message是否为null，为null就再把自己这个倒计时开一遍，直到不为null

**Comment by zuihou** [comment]
<img width="1357" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/8500410/9fe9417a-2694-40d4-bbb3-70e0df8ab35e">


刚看了n-ui文档，看到这个函数， `createDiscreteApi `， 不知道这样子同时混用`createDiscreteApi` 和 `useMessage` 会产生什么影响？
```
let msg = undefined;
if (msg == undefined) {
     const {  message }  = createDiscreteApi(
        ['message'],
      );
    msg = message;
}
msg?.error(message);
```
