### ISSUE TITLE
eslint.config导致 格式化时组件自动转化PascalCase 失效

### ISSUE THREAD

**Issue by Li-0221** [soybeanjs/soybean-admin#348]
🥲使用kebab-case写法不报错
![image](https://github.com/soybeanjs/soybean-admin/assets/75083207/f5043769-c917-49a8-bed1-e86d6046e2b2)

😃注释掉eslint.config的这段，正常提示，且在保存代码时会将`<n-card>`转化为`<NCard>`
![image](https://github.com/soybeanjs/soybean-admin/assets/75083207/45d8974f-95e8-4545-b96c-d9521ff75e17)

**Comment by Li-0221** [comment]
https://docs.soybeanjs.cn/ 文档右上角的qq群加不进去

![image](https://github.com/soybeanjs/soybean-admin/assets/75083207/4f6f71ea-549d-4692-82ca-e4930c821197)

**Comment by Azir-11** [comment]
> https://docs.soybeanjs.cn/ 文档右上角的qq群加不进去
> 
> ![image](https://private-user-images.githubusercontent.com/75083207/312331424-4f6f71ea-549d-4692-82ca-e4930c821197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTEyNDMsIm5iZiI6MTcxMDMxMDk0MywicGF0aCI6Ii83NTA4MzIwNy8zMTIzMzE0MjQtNGY2ZjcxZWEtNTQ5ZC00NjkyLTgyY2EtZTQ5MzBjODIxMTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA2MjIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMWJlODY5MDk1YzMxZTM0NzM5OWZmODE0NmYwZTlkYjI2NTQxMjFmODFmMDdmMWI4YjYwNDkxYTU0OGQxOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DCcqyxR6FwN1I3CpWukY-q-PB1CcIOFERMT-ACyD70w)

711301266

**Comment by honghuangdc** [comment]
fixed 8143b00

**Comment by Li-0221** [comment]
> fixed [8143b00](https://github.com/soybeanjs/soybean-admin/commit/8143b0063cdcffd8176688096659adcbdd5aa386)

谢谢🙏
