### ISSUE TITLE
切换tab时如何控制是否刷新目标tab

### ISSUE THREAD

**Issue by checkZH** [soybeanjs/soybean-admin#351]
目前默认配置好像是切换tab时都会刷新目标tab
能否设置不刷新或通过参数配置某些刷新某些不刷新
想问是否有地方可以配置,或者在哪里可以写逻辑自己实现

**Comment by Azir-11** [comment]
你是指`keepalive`吗

**Comment by honghuangdc** [comment]
缓存了就行，加个keepAlive

**Comment by checkZH** [comment]
@Azir-11  @honghuangdc  感谢回复
