### ISSUE TITLE
调用后台接口成功但是解构拿不到返回值

### ISSUE THREAD

**Issue by 15317668327** [soybeanjs/soybean-admin#354]
![image](https://github.com/soybeanjs/soybean-admin/assets/88755182/496e5e75-be5c-418e-a9ac-4d98aa35340e)
![image](https://github.com/soybeanjs/soybean-admin/assets/88755182/0e1488f9-a5b7-48ce-99dc-de6668962c67)
![image](https://github.com/soybeanjs/soybean-admin/assets/88755182/da4a427f-632a-42d1-9a9f-8ffbf560da74)
![image](https://github.com/soybeanjs/soybean-admin/assets/88755182/62e8d72c-45f1-476c-b22b-238c76bd3861)
![image](https://github.com/soybeanjs/soybean-admin/assets/88755182/80a1a84d-d551-4ed4-82f7-394ea88c2c85)

**Comment by honghuangdc** [comment]
判断后端是否表示请求成功 isBackendSuccess

<img width="851" alt="截屏2024-03-19 18 53 54" src="https://github.com/soybeanjs/soybean-admin/assets/49704545/94ae4047-def4-4e7a-93c8-eb0601114e24">

**Comment by 15317668327** [comment]
我改成了我使用的code=200，为什么还是不可以呢





在 2024-03-19 18:54:48，"Soybean" ***@***.***> 写道：

判断后端是否表示请求成功 isBackendSuccess

2024-03-19.18.53.54.png (view on web)

**Comment by 15317668327** [comment]
![image](https://github.com/soybeanjs/soybean-admin/assets/88755182/e34c9a9d-3683-42f2-9055-200e358cf24a)
response的data中都已经有我返回的数据量，但是解构得到的值还是null

**Comment by Azir-11** [comment]
首先确定你用的是`createRequest `还是`createFlatRequest`
`createRequest`: 返回的请求实例直接返回 Axios 响应数据（可转换)。
`createFlatRequest`: 返回的请求实例会将响应数据和错误信息包装在一个扁平的对象中，以统一的格式返回结果。
具体细节请看文档：https://docs.soybean.pro/zh/guide/request.html
还解决不了加QQ群，我远程帮你解决

**Comment by 15317668327** [comment]
createRequest和createFlatRequest都用了试过，能否远程协助一下，QQ群加群校验没通过，qq:2723271733









在 2024-03-19 23:33:14，"青菜白玉汤" ***@***.***> 写道：

首先确定你用的是createRequest 还是createFlatRequest
createRequest: 返回的请求实例直接返回 Axios 响应数据（可转换)。
createFlatRequest: 返回的请求实例会将响应数据和错误信息包装在一个扁平的对象中，以统一的格式返回结果。
具体细节请看文档：https://docs.soybean.pro/zh/guide/request.html
还解决不了加QQ群，我远程帮你解决

**Comment by Azir-11** [comment]
711301266
