### ISSUE TITLE
监听当为手机模式后自动切换为垂直模式，再恢复非手机模式后，无法恢复到用户自定义的模式

### ISSUE THREAD

**Issue by vastsa** [soybeanjs/soybean-admin#361]
监听当为手机模式后自动切换为垂直模式，再恢复非手机模式后，无法恢复到用户自定义的模式
<img width="1622" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/48862574/e366c1ce-d5c7-4709-8976-a868f7f68c35">
<img width="1623" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/48862574/c797ccba-ae0d-4127-bbbf-c90e699e23e3">
<img width="1622" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/48862574/6db54e64-aea6-41e2-8f55-cf650fde9c8a">
我这边尝试新增一个usermode来缓存
<img width="839" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/48862574/02f0c46f-bafb-4e24-9347-e8974b8f2b4c">
但是，顶部菜单混合模式和左侧菜单混合模式，重新恢复非手机模式后报错。
<img width="575" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/48862574/a4ead3af-9085-491c-8e68-5f25023195e0">

**Comment by honghuangdc** [comment]
这个功能是没有必要的。本身兼容移动端就是直接在移动设备上展示，而不断在移动端和PC端的来回变换是没有考虑的，只要保证各自的布局没有问题就可以

**Comment by vastsa** [comment]
有道理
