### ISSUE TITLE
[Bug]: createDefaultModel设置了默认值，NRadio没有默认选中

### ISSUE THREAD

**Issue by SheepYang1993** [soybeanjs/soybean-admin#363]
### 软件版本

51d77589

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

```
function createDefaultModel(): Model {
  return {
    name: '',
    code: '',
    desc: '',
    status: '1'
  };
}
```
```
<NFormItem :label="$t('page.manage.role.roleStatus')" path="status">
  <NRadioGroup v-model:value="model.status">
    <NRadio v-for="item in enableStatusOptions" :key="item.value" :value="item.value" :label="$t(item.label)" />
  </NRadioGroup>
</NFormItem>
```

### 期望的结果是什么？

NRadio默认选中

### 实际的结果是什么？

NRadio没有默认选中

**Comment by honghuangdc** [comment]
我这边没有复现，正常的可以展示值
<img width="462" alt="截屏2024-03-25 11 10 39" src="https://github.com/soybeanjs/soybean-admin/assets/49704545/ad66c60a-7e0c-43c4-9458-4f0b9d5568ca">

<img width="427" alt="截屏2024-03-25 11 10 30" src="https://github.com/soybeanjs/soybean-admin/assets/49704545/c14ac29f-b09d-4d7c-8036-d6b6f4cb869e">

**Comment by Azir-11** [comment]
会不会是enableStatusOptions设置的值是number的，model提供了string
不是的话提供一个复现吧
[codesandbox.io](https://codesandbox.io/s/6wppzh)https://[codesandbox.io/s/6wppzh](https://codesandbox.io/s/6wppzh)

**Comment by SheepYang1993** [comment]
> 会不会是enableStatusOptions设置的值是number的，model提供了string 不是的话提供一个复现吧 [codesandbox.io](https://codesandbox.io/s/6wppzh)
对，enableStatusOptions改成了number了，然后就不生效了

**Comment by SheepYang1993** [comment]
@Azir-11 请教一下为什么number会没有生效？

**Comment by Azir-11** [comment]
> @Azir-11 请教一下为什么number会没有生效？

建议日常开发用`===`而不是`==`，`'1'`和`1`是完全不同的两个东西，value不相等自然不会选中

**Comment by SheepYang1993** [comment]
> > @Azir-11 请教一下为什么number会没有生效？
> 
> 建议日常开发用`===`而不是`==`，`'1'`和`1`是完全不同的两个东西，value不相等自然不会选中

`===`而不是`==`这个我理解，model.status改成number了，还是没有选中。emmm，我自己再看看吧

**Comment by honghuangdc** [comment]
enableStatusRecord 的key虽然改成了number,但是通过转换得到的enableStatusOptions的value变成了string, 所以匹配不了

**Comment by SheepYang1993** [comment]
enableStatusOptions我也有改成number
```
export function transformRecordToOption2<T extends Record<number, string>>(record: T) {
  return Object.entries(record).map(([value, label]) => ({
    value,
    label
  })) as CommonType.Option<keyof T>[];
}
```

**Comment by SheepYang1993** [comment]
谢谢大佬指点，应该还是transformRecordToOption2转换的问题，没转成number
