### ISSUE TITLE
v1.1 版本计划

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin#364]
TODO list

- [ ] ~~#365~~
- [x] #366
- [x] #368
- [x] #370 
- [ ] ~~#372~~
- [x] #385 
- [x] #388 
- [x] #400
- [x] #403

**Comment by SheepYang1993** [comment]
下拉框Select能支持分页异步加载吗？

**Comment by honghuangdc** [comment]
> 下拉框Select能支持分页异步加载吗？

这个你应该去naive-ui那里去提issues

**Comment by Azir-11** [comment]
权限按钮结合进路由的meta内

**Comment by honghuangdc** [comment]
> 权限按钮结合进路由的meta内

可以的，目前我是直接把按钮放在用户信息里面

**Comment by honghuangdc** [comment]
> > 权限按钮结合进路由的meta内
> 
> 可以的，目前我是直接把按钮放在用户信息里面

已经提了 #366 特性

**Comment by honghuangdc** [comment]
#368 请求错误信息提示处理

**Comment by qiaojinxia** [comment]
添加菜单页面 很多meta很多字段没添加 比如 hideInMenu i18nKey component ,添加子菜单 页面也不会显示父菜单

**Comment by Azir-11** [comment]
灰度模式（在某些特殊日期可以支持开启）

**Comment by Azir-11** [comment]
### 让tab栏的刷新按钮更彻底得刷新

目前在keepalive页面，刷新触发后只是播放了一个动画，并未真正刷新，考虑在触发刷新的时候，将当前的keepalive移除，异步添加回来，让页面能真正刷新

**Comment by CrazyRock-baochengrui** [comment]
登录界面的默认用户名的密码怎么修改

**Comment by Azir-11** [comment]
> 登录界面的默认用户名的密码怎么修改

1、在`pwd-login.vue`中的 `model`中进行修改
2、请打开一个新的issue进行交流，这个issue是用来记录版本计划的

**Comment by CrazyRock-baochengrui** [comment]
> > 登录界面的默认用户名的密码怎么修改
> 
> 1、在`pwd-login.vue`中的 `model`中进行修改 2、请打开一个新的issue进行交流，这个issue是用来记录版本计划的

![00](https://github.com/soybeanjs/soybean-admin/assets/91175110/aa15c9ac-7488-4c63-9860-32eece13b602)
![01](https://github.com/soybeanjs/soybean-admin/assets/91175110/26e9e8d5-79a2-4128-9ca3-c8a4aff18c06)
按照这样修改后，登录失败，用默认的Soybean，123456又可以登录

**Comment by CrazyRock-baochengrui** [comment]
![00](https://github.com/soybeanjs/soybean-admin/assets/91175110/27a5bd4a-fefa-47a7-9be4-cdf28ac5ef9e)
![01](https://github.com/soybeanjs/soybean-admin/assets/91175110/2a198c46-1ebb-4599-b40f-72d47acec2bf)

**Comment by CrazyRock-baochengrui** [comment]
![00](https://github.com/soybeanjs/soybean-admin/assets/91175110/880130bf-ac09-46d5-b393-f0c4a19465e4)
![01](https://github.com/soybeanjs/soybean-admin/assets/91175110/12b1f299-6090-4c48-9f4d-b30ea9c039ba)

**Comment by Azir-11** [comment]
对上你自己的接口啊，我们的接口不支持你的admin的，你要去对接自己的后端

**Comment by honghuangdc** [comment]
> 灰度模式（在某些特殊日期可以支持开启）

#385

**Comment by Azir-11** [comment]
本地储存可添加前缀，支持同一域下部署多个前端项目的需求

**Comment by Azir-11** [comment]
table的操作列的button type改为text类型的

**Comment by honghuangdc** [comment]
v1.1.0 已发布 beta 21df57b

**Comment by honghuangdc** [comment]
已发布 e7f0a30
