### ISSUE TITLE
[Feature]: 系统管理 - 菜单管理支持更多属性配置

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin#370]
支持更多属性配置，参照 src/typings/router.d.ts 类型定义

**Comment by honghuangdc** [comment]
计划 v1.1 中 实现 #364

**Comment by haitang-psj** [comment]
这个需要后端配合吧，目前菜单数据返回结构太少，而且返回的RouteMeta对象在一整个对象当中，应该在后端也设置相对应的meta字段使用Json/String存储，查询到前台解析字段展示，添加的话封装成对应meta字符串，这样添加应该合理

**Comment by Azir-11** [comment]
> 这个需要后端配合吧，目前菜单数据返回结构太少，而且返回的RouteMeta对象在一整个对象当中，应该在后端也设置相对应的meta字段使用Json/String存储，查询到前台解析字段展示，添加的话封装成对应meta字符串，这样添加应该合理

1、菜单管理会跟进type定义的所有信息
2、全部存成json的话健壮性会低很多，也不利于维护，如果需要的话可以自行处理成json/String

**Comment by honghuangdc** [comment]
实现 #411
