### ISSUE TITLE
[Feature]: 支持构建离线的iconify图标

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin#372]

**Comment by honghuangdc** [comment]
计划 v1.1 #364

**Comment by honghuangdc** [comment]
目前对于一些内网环境，项目可以配置环境变量 VITE_ICONIFY_URL ，表示内网环境 @iconify/icon 的资源获取地址
经探索，@iconify/json的全部json文件大小有300多兆，离线构建会大大影响产物的大小。如果想按需构建json，是一个不错的想法，但是在线想使用任意的图标集还是没法实现，因此，这个功能暂不实现，对于按需加载json，会提供文档说明，手动调用`@iconify/vue`提供的`addCollection`添加指定图标集即可。

**Comment by honghuangdc** [comment]
计划 https://github.com/soybeanjs/soybean-admin-docs/issues/55

**Comment by Thinking80s** [comment]
最新的版本支持了吗？

**Comment by Azir-11** [comment]
> 最新的版本支持了吗？

支持了

**Comment by Thinking80s** [comment]
> > 最新的版本支持了吗？
> 
> 支持了

只能按需加载json，手动调用@iconify/vue提供的addCollection添加吧？不能针对使用的任意的图标集进行按需打包
