### ISSUE TITLE
[Bug]: 头部tab标签关闭 菜单二子菜单首页 页面空白控制台报错

### ISSUE THREAD

**Issue by ZTH520** [soybeanjs/soybean-admin#375]
### 软件版本

v1.0.0

### 运行环境

MacOS

### 运行架构

None

### 重现步骤

![image](https://github.com/soybeanjs/soybean-admin/assets/37199360/a403c3ba-4117-4e7c-b483-85f23577b7cf)

### 期望的结果是什么？

显示正确的菜单内容

### 实际的结果是什么？

控制台报错

**Comment by honghuangdc** [comment]
估计是本地开发时遇到的，暂时不能复现，你能100%复现吗

**Comment by ZTH520** [comment]
> 估计是本地开发时遇到的，暂时不能复现，你能100%复现吗

是网页上发现的，快速的来回切换tab标签选中与关闭会出现

**Comment by honghuangdc** [comment]
给个必现的操作步骤，或者录个视频

**Comment by honghuangdc** [comment]
如不能复现，今天之内会关掉该issue
