### ISSUE TITLE
登录界面的默认用户名的密码怎么修改

### ISSUE THREAD

**Issue by Azir-11** [soybeanjs/soybean-admin#384]
登录界面的默认用户名的密码怎么修改

_Originally posted by @CrazyRock-baochengrui in https://github.com/soybeanjs/soybean-admin/issues/364#issuecomment-2044154300_

**Comment by Azir-11** [comment]
后续在这里补充，不要再去版本计划里发无关内容了

**Comment by honghuangdc** [comment]
本项目是基于apifox的接口，可以自行创建apifox然后接入
参考项目的apifox接口 https://apifox.com/apidoc/shared-35c8727a-d3ab-47e9-8863-ef8e37df6887?pwd=F6LN1ArU
