### ISSUE TITLE
[Bug]: 左侧菜单混合模式布局二级侧边菜单【固定】功能异常

### ISSUE THREAD

**Issue by redwolf1996** [soybeanjs/soybean-admin#407]
### 软件版本

main

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

1.在配置项里选择【左侧菜单混合模式布局】
2.在二级侧边菜单点击右上角图钉固定
3.将鼠标移动至二级侧边菜单右边的区域
4.并没有固定
![image](https://github.com/soybeanjs/soybean-admin/assets/9690393/e6178b66-2326-475d-9474-08fdbb174b0e)

### 期望的结果是什么？

1.期望点击【固定】按钮后，能固定住，鼠标移动到二级菜单右侧不要将二级菜单缩回去
2.固定的时候右侧区域缩小，取消固定的时候右侧区域变大实现响应式
3.选择了固定就一直显示二级菜单，重新登录后不要消失（从动机上来说，选择这个模式的目的就是希望能一直显示这个二级菜单能直接看到更多的信息，固定这个操作对于操作者而言实际大多数情况下并不想是一个临时操作，除非是右边空间实在不足了才会取消固定吧，所以希望不要消失 ……^^）

### 实际的结果是什么？

1.鼠标移动到二级菜单右侧二级菜单缩回去了
2.固定的时候右侧区域变大，取消固定的时候右侧区域变小，目前这个顺序是倒过来了
3.重新登录后如果之前是选择的固定二级菜单，二级菜单并没有出现

**Comment by honghuangdc** [comment]
提示文本反了

**Comment by honghuangdc** [comment]
其他的操作逻辑都是正常的

**Comment by Azir-11** [comment]
始终固定二级菜单可以推一个新的布局模式专门做，现在这个固定的意思其实是二级菜单是覆盖content还是顶开content

**Comment by redwolf1996** [comment]
> 其他的操作逻辑都是正常的

额，文本是反了，我仔细看了下，好像逻辑没问题，另外有个问题就是一刷新（或者此时我输入一个不存在的地址导致404）就又回到之前的默认布局模式了，还有个缩放窗口导致回到默认布局模式没动态切换的问题，我提了另外一个issue

**Comment by redwolf1996** [comment]
> 始终固定二级菜单可以推一个新的布局模式专门做，现在这个固定的意思其实是二级菜单是覆盖content还是顶开content

是的~
