### ISSUE TITLE
[Bug]: 布局模式因窗口大小的变化而无法响应式恢复的问题

### ISSUE THREAD

**Issue by redwolf1996** [soybeanjs/soybean-admin#408]
### 软件版本

main

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

1.配置里选择混合模式布局
2.将窗口缩小至手机尺寸大小
3.再将窗口最大化恢复至正常大小
4.再查看配置项里的【布局模式】
![image](https://github.com/soybeanjs/soybean-admin/assets/9690393/2e353793-4d25-455f-9465-78f2d7f37580)

### 期望的结果是什么？

期望布局模式还是之前选择的【混合模式】

### 实际的结果是什么？

布局模式在窗口缩小后临时变成了默认的左侧菜单模式，但是当窗口变化放大后，没有将这种布局模式切换回去

### 补充说明（可选）
刷新页面或者页面404也会导致布局模式回到默认模式
_No response_

**Comment by honghuangdc** [comment]
参照问题 #361

**Comment by Azir-11** [comment]
该问题属于短期不会处理的无关紧要bug，未来有余力了可能会修复，如果遇到了某个场景必须解决该问题的话欢迎重新open并进一步交流

**Comment by redwolf1996** [comment]
> 该问题属于短期不会处理的无关紧要bug，未来有余力了可能会修复，如果遇到了某个场景必须解决该问题的话欢迎重新open并进一步交流
好的，等我看懂大佬代码了到时候提个pr, 现在不敢改:( ,  另外刷新页面或者页面404也会导致布局模式回到默认模式，这个看下呢

**Comment by honghuangdc** [comment]
> > 该问题属于短期不会处理的无关紧要bug，未来有余力了可能会修复，如果遇到了某个场景必须解决该问题的话欢迎重新open并进一步交流
> > 好的，等我看懂大佬代码了到时候提个pr, 现在不敢改:( ,  另外刷新页面或者页面404也会导致布局模式回到默认模式，这个看下呢

本地开发阶段是不会缓存主题配置的，只会默认取 src/theme/settings.ts 的配置
