### ISSUE TITLE
[Bug]: 修正编辑表单弹框时的引用类型数据重置问题

### ISSUE THREAD

**Issue by jensen-999** [soybeanjs/soybean-admin#415]
### 软件版本

v1.0.8

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

打开operate-modal.vue文件，
修改创建Model的函数
```
function createDefaultModel(): Model {
  return {
    customName: '匿名顾客',
    customPhone: '',
    originalPrice: 0,
    receivedAmount: 0,
    profit: 0,
    orderProductList<object[]>: [], // 增加引用数据类型
    image: '',
    remark: ''
  }
}
```
点击某一表格行的编辑按钮。
打开编辑弹框。
修改orderProductList数据，并点击取消。
检查该行数据，引用类型数据未重置。

### 期望的结果是什么？

无论用户是否保存编辑，点击取消后，所有数据应重置为编辑前的状态，确保数据的一致性和准确性。

### 实际的结果是什么？

点击取消后，基本数据类型的数据重置为编辑前的状态，但引用类型数据没有被重置。
![1](https://github.com/soybeanjs/soybean-admin/assets/121743971/b87d9ddb-0145-4db9-b075-e668f644990a)
![2](https://github.com/soybeanjs/soybean-admin/assets/121743971/6b67c2ff-1a0b-4168-bb97-618494e782d2)
![3](https://github.com/soybeanjs/soybean-admin/assets/121743971/9d2c1ffe-a074-4c57-98d5-a70501825d79)

**Comment by honghuangdc** [comment]
你这代码是自己写的，自己处理下就行。

**Comment by honghuangdc** [comment]
你对比下，用户管理里面有个 userRoles, 是引用数据，没有你说的这个问题

**Comment by honghuangdc** [comment]
待复现
