### ISSUE TITLE
请问列表详情页该如何创建目录

### ISSUE THREAD

**Issue by izrio** [soybeanjs/soybean-admin#416]
有以下菜单：活动管理 -> 活动列表

点击【活动列表】展示table列表页面，再点击某一行table row， 跳转到【活动详情页面】

同时面包屑展示 活动管理 -> 活动列表 -> 活动详情

活动详情页面在menu中是隐藏的，选中【活动列表】 activeMenu为活动管理，跳转【活动详情】 activeMenu为活动列表

请问这种情况下，views目录结构该是怎样的

**Comment by Azir-11** [comment]
文件夹结构参考：https://docs.soybean.pro/zh/guide/router/structure.html#%E4%BA%8C%E7%BA%A7%E8%B7%AF%E7%94%B1
activeMenu参考路由meta的activeMenu属性

**Comment by honghuangdc** [comment]
```
- activity-manage
    - activity-list
    - activity-detail
```
活动列表和活动详情同级就行，然后活动详情的路由属性meta里面配置 activeMenu: 'activity-list'

**Comment by 0zcl** [comment]
> > > ```
> > > - activity-manage
> > >     - activity-list
> > >     - activity-detail
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 活动列表和活动详情同级就行，然后活动详情的路由属性meta里面配置 activeMenu: 'activity-list'
> > 
> > 
> > 这样面包屑无法展示：面包屑展示 活动管理 -> 活动列表 -> 活动详情， 只能展示：活动管理 -> 活动详情，了 [@honghuangdc](https://github.com/honghuangdc) [@Azir-11](https://github.com/Azir-11)
> 
> 受限于旧版的路由插件，这个功能很难完成，1.4 版本会更新全新的路由插件，届时会修复这个问题，可以期待一下

好的，期待。1.4版本有计划啥时候出吗

**Comment by Azir-11** [comment]
> 
> 好的，期待。1.4版本有计划啥时候出吗

已经在开发中了，具体时间没法保证
