### ISSUE TITLE
v1.2 Iteration Plan 迭代计划

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin#419]
### Todo List
- [x] #420
- [x] #459
- [x] ~~#365~~
- [x] ~~#379~~
- [x] ~~#439~~

**Comment by honghuangdc** [comment]
等先把项目文档补充完善后再着手 1.2 版本的迭代

**Comment by kenixFog** [comment]
1、左侧菜单，支持鼠标左右拖拽调整宽度
2、左侧菜单，展开菜单背景颜色和主菜单背景进行区分

**Comment by Azir-11** [comment]
> 1、左侧菜单，支持鼠标左右拖拽调整宽度 2、左侧菜单，展开菜单背景颜色和主菜单背景进行区分

1、没有必要，可以直接在主题抽屉设置了，并且该功能很少系统会用，暂时不考虑
2、有示例效果可以看看么？有的话可以在新issue里提出，一起讨论一下

**Comment by kenixFog** [comment]
第一个是我想错场景了，确实很少用到~~
第二个，效果如下
![image](https://github.com/soybeanjs/soybean-admin/assets/29566225/c0eae68a-beec-436a-9786-e5ab765c1d12)

**Comment by honghuangdc** [comment]
release v1.2.0 4b63bbc
