### ISSUE TITLE
是否支持默认的chatbot ai组件

### ISSUE THREAD

**Issue by dawsongzhao0523** [soybeanjs/soybean-admin#434]
未来ai聊天组件将是趋势我们是否有计划内置这样的组件，开箱即用。

**Comment by Azir-11** [comment]
目前有计划，但是优先级不高

**Comment by dawsongzhao0523** [comment]
感觉这一块，目前还是比较火的，社区原生支持这块的admin也比较少，建议是否可以提高优先级。增强差异化竞争力

**Comment by Azir-11** [comment]
> 感觉这一块，目前还是比较火的，社区原生支持这块的admin也比较少，建议是否可以提高优先级。增强差异化竞争力

我们做的是通用后台，以满足大部分人为主，加上之后肯定会对系统造成侵入，所以这类具体功能的接入还有待商榷

**Comment by dawsongzhao0523** [comment]
理解

**Comment by honghuangdc** [comment]
这种插件需要自己去对接
如果想集成到SoybeanAdmin的话，欢迎提PR到example分支
