### ISSUE TITLE
是否考虑支持字节的vwind vchart 等产品

### ISSUE THREAD

**Issue by dawsongzhao0523** [soybeanjs/soybean-admin#435]

**Comment by Azir-11** [comment]
vwind方便提供一下文档码？
vchart倒是搜到了好几个，可以提供一下您说的这个vchart的地址吗？

main分支会尽量保持干净的依赖，如无必要不会引入个性化的内容，合适的话可以在example分支里增加对应示例

**Comment by dawsongzhao0523** [comment]
https://www.visactor.io/ 字节跳动的这个开源组件

**Comment by Azir-11** [comment]
> https://www.visactor.io/ 字节跳动的这个开源组件

可以考虑在example分支里增加对应示例，时间不能保证，也欢迎您参与贡献

**Comment by honghuangdc** [comment]
这种插件需要自己去对接
如果想集成到SoybeanAdmin的话，欢迎提PR到example分支
