### ISSUE TITLE
[Bug]: 打开新的tab展示不全

### ISSUE THREAD

**Issue by checkZH** [soybeanjs/soybean-admin#445]
### 软件版本

1.1.0

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

当有tab栏已经有很多tab时,此时打开一个新的tab,例如该tab在路由中定义的内容为   ABCDEFG,但是在页面使用tabStore.setTabLabel 修改了Tab的label 且长度大于之前的内容,则会导致显示不全

![image](https://github.com/soybeanjs/soybean-admin/assets/47131421/c8003a4e-d7a5-4f52-92e5-eca6e2e51b1b)

### 期望的结果是什么？

![image](https://github.com/soybeanjs/soybean-admin/assets/47131421/12b57e48-b1b5-4090-917e-4c964b0c0f26)

### 实际的结果是什么？

![image](https://github.com/soybeanjs/soybean-admin/assets/47131421/c8003a4e-d7a5-4f52-92e5-eca6e2e51b1b)

### 补充说明（可选）

当

**Comment by honghuangdc** [comment]
该问题已在版本v1.0.1中修复过 cc53997，请更新版本

**Comment by checkZH** [comment]
这个解决的是过长中间出现空白的问题,实际上当修改label长度时会出现我上面展示的情况,因为打开tab使用的是默认的label,但是修改label是在打开tab之后,修改之后会导致实际渲染的Tab宽度比修改之前宽,这样就会有一部分被隐藏,我目前的处理办法是监听label发生变化再执行一次scrollToActiveTab,不知道是否有更佳实现方式
```
watch(
  () => tabStore.activeChange,
  () => {
    scrollToActiveTab();
  }
);
```
