### ISSUE TITLE
[Bug]: 左侧菜单混合模式，「固定」后无效

### ISSUE THREAD

**Issue by majinkai** [soybeanjs/soybean-admin#451]
### 软件版本

1.1.2

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

![image](https://github.com/soybeanjs/soybean-admin/assets/3540799/47ea1fac-1733-4449-9dbc-7efc2a7761a0)

### 期望的结果是什么？

1. 点击固定后，展开的菜单应该常驻
2. 固定/取消固定，按钮偏移一点更加美观

### 实际的结果是什么？

1. 点击固定后，展开的菜单会自动收缩回去
2. 固定/取消固定，按钮贴边不美观

**Comment by Azir-11** [comment]
这个固定的逻辑是没有问题的，目前就是这么设计的，贴边问题会在近期解决
