### ISSUE TITLE
[Bug]: 应该显示角色名称，这类没意义的角色编码没有人可以记清楚

### ISSUE THREAD

**Issue by ww2766** [soybeanjs/soybean-admin#452]
### 软件版本

最新

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

![屏幕截图 2024-05-29 131253](https://github.com/soybeanjs/soybean-admin/assets/145252184/0e957f65-6c5d-445d-8d55-605cb29bf31b)

### 期望的结果是什么？

使用角色名称进行显示

### 实际的结果是什么？

当前是使用角色编码显示

**Comment by Azir-11** [comment]
这玩意是你们具体的系统里去做设计对接展示的，我们只是提供一个可能的示例而已
