### ISSUE TITLE
[Bug]: 关于切换权限的问题

### ISSUE THREAD

**Issue by MscZhao** [soybeanjs/soybean-admin#457]
### Software Version

ALL

### Operating Environment

Windows (64)

### Operating Architecture

None

### Reproduce Steps

如果当前登录的是普通用户的账户，通过浏览器的Localstorage界面去修改userinfo的value中的buttos的值，例如加入超级管理员的按钮权限代码，刷新页面，普通用户就可以看到超级管理员才能看到的按钮。

### What is the expected result?

建议手动刷新页面时，重新获取一次userinfo,重新写入Localstorage。

### What is the actual result?

建议手动刷新页面时，重新获取一次userinfo的值, 重新写入Localstorage。

**Comment by Azir-11** [comment]
确实是个问题，其他的储存项也可能会出现类似的问题，可以试试对本地储存加密？这样可能更彻底一点，具体的方案有待讨论，预期1.2版本会对此问题进行修复

**Comment by MscZhao** [comment]
好的，能否考虑一下我的建议

**Comment by Azir-11** [comment]
> 好的，能否考虑一下我的建议

会考虑的，但是不确定是否最终选用，选择的方案也会继续在这里进行说明

**Comment by limuen** [comment]
我们以前和现在的vue和react的切换权限方案都是只要刷新，就会重新去走获取权限的接口，个人目前认为是最好的方案，存到本地刷新没去重新调接口，可能就跟上面的兄弟一样，可以看到其他角色的按钮（供参考...

**Comment by honghuangdc** [comment]
我先提个issues记录下

**Comment by honghuangdc** [comment]
已计划 #459
