### ISSUE TITLE
【无关痛痒】在学习仓库代码时的小疑问

### ISSUE THREAD

**Issue by orangelckc** [soybeanjs/soybean-admin#461]
在学习项目代码的时候，发现已经引入了 `lodash` 包，但是发现有的代码如果使用 `lodash` 提供的方法书写会更简洁，

想问问项目是否支持在发现类似的可以简化的代码逻辑时，接受简化代码写法的 `PR`，这里有个例子：

https://github.com/soybeanjs/soybean-admin/blob/086bad474eebfa38c91c7795d280251cc15de1fd/src/store/modules/app/index.ts#L44C1-L48C25

![1](https://github.com/soybeanjs/soybean-admin/assets/48410934/998df53e-895c-4096-add9-2d2cdce84983)

如果仓库接受类似优化代码，我会发几个 `PR` 上来 😃

**Comment by honghuangdc** [comment]
这个delay的我觉着还是没有原本的代码清晰，而且delay不是基于Promise，如果后续有添加其他逻辑，那都得往回调函数里面扔

**Comment by honghuangdc** [comment]
其他的如果现有代码比较冗余，有能优化的，可以发出来看看，讨论下

**Comment by Azir-11** [comment]
目前项目里好像只有`cloneDeep`用了，建议把lodash干掉
