### ISSUE TITLE
建议将顶部菜单布局改为顶部一级菜单和侧边栏子菜单的布局，这样更符合用户的直觉和使用习惯。

### ISSUE THREAD

**Issue by wcldyx** [soybeanjs/soybean-admin#474]
### 软件版本

1.1.3

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

无

### 期望的结果是什么？

如题

### 实际的结果是什么？

如题

**Comment by Azir-11** [comment]
重复 #365
