### ISSUE TITLE
[Bug]: 挺好的一个东西，跟甜蜜蜜扯上什么关系。踢出甜蜜蜜

### ISSUE THREAD

**Issue by mimimiaomiao1** [soybeanjs/soybean-admin#475]
### 软件版本

11

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

踢出甜蜜蜜

### 期望的结果是什么？

踢出甜蜜蜜

### 实际的结果是什么？

踢出甜蜜蜜

### 日志记录（可选）

```golang
踢出甜蜜蜜
```

### 补充说明（可选）

踢出甜蜜蜜

**Comment by honghuangdc** [comment]
你和他有恩怨，请自行处理，别在这刷存在感。
