### ISSUE TITLE
v1.3 Iteration Plan 迭代计划

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin#480]
- [x] #365
- [x] #379
- [x] #503
- [x] #504
- [x] #518

**Comment by honghuangdc** [comment]
- [x] #365
- [x] #379

**Comment by honghuangdc** [comment]
预计时间：8月份

**Comment by Monkey0118** [comment]
emmm 我觉得大佬可以考虑下一键生产后端crud+ddl  可以极大解决后续开发工作

**Comment by Azir-11** [comment]
> emmm 我觉得大佬可以考虑下一键生产后端crud+ddl 可以极大解决后续开发工作

根据接口和类型可以做代码生成器，但是近期不会考虑，未来可能会有

**Comment by honghuangdc** [comment]
release v1.3.0 f73f70c
