### ISSUE TITLE
[Bug]: 侧边栏按钮图标消失

### ISSUE THREAD

**Issue by lzb-libra** [soybeanjs/soybean-admin#483]
### Software Version

1.2.1

### Operating Environment

Other (please specify below)

### Operating Architecture

None

### Reproduce Steps

我不确定这是不是你们就是这么设计的，但是我认为是一个bug。使用手机打开项目，顶部左侧有个菜单图标，点击后在左侧弹出菜单，点击其他区域后会自动关闭菜单弹窗，但是顶部左侧的菜单图标消失不见了，实际上点击同一个区域菜单还是能弹出来的。我是在2024-06-07重新拉取的代码。
![Screenshot_20240607_163228_com huawei browser_edi(1)](https://github.com/soybeanjs/soybean-admin/assets/63389341/ac61e231-0eb4-4187-8c09-8097cada377e)
![Screenshot_20240607_163235_com huawei browser_edi(1)](https://github.com/soybeanjs/soybean-admin/assets/63389341/002b34f1-e224-439a-ad85-167c6290c90d)

### What is the expected result?

在手机上进行上述操作后菜单图标不消失

### What is the actual result?

在手机上进行上述操作后菜单图标消失

**Comment by lzb-libra** [comment]
在补充几点，出现图标消失的问题时在华为手机上，使用的是系统浏览器。在三星手机上，主题模式不管怎么切换都是暗黑模式。

**Comment by Azir-11** [comment]
图标的这个问题很早之前就遇到过了，不限于手机和浏览器，但是我找了三次都没找到是什么问题，很怪

**Comment by KickCashew** [comment]
我试了一下在小米手机的系统浏览器也会出现这个问题
我的解决方法是 在menu-toggler.vue文件中 添加一个key 让组件强制刷新
![image](https://github.com/soybeanjs/soybean-admin/assets/76767398/e813fecc-fa36-4896-a173-ec44dcf2752c)

**Comment by honghuangdc** [comment]
1. 先用给组件加key的方式去解决，key取值 collapsed 即可
2. 暗黑模式的兼容性这个就不处理了，有时间精力解决的朋友欢迎PR
