### ISSUE TITLE
是否有精简版、非国际化版等

### ISSUE THREAD

**Issue by Mophar-gift** [soybeanjs/soybean-admin#484]
soybean-admin 不论是界面还是交互效果都十分的漂亮，代码规范质量高，是否有精简版提供？

**Comment by Azir-11** [comment]
目前的main分支即精简版，更多的示例都迁移到example分支了，非国际化版本涉及变动较多，短期不会提供

**Comment by Azir-11** [comment]
可以考虑出一个没有国际化的分支

**Comment by Mophar-gift** [comment]
感谢您的答复，期待

**Comment by honghuangdc** [comment]
可以提供一个不使用国际化的文档介绍，单独的分支就不提供了
1. 在路由插件注册的地方 `build/plugins/router.ts` 变更一下 onRouteMetaGen，把i18nKey去掉，后续只需要配置路由数据的title即可

**Comment by Schaffer-W** [comment]
有些页面也用了国际化，是不是可以全局搜索$t删除，然后把内容替换成想要的语言内容。

**Comment by Azir-11** [comment]
> 有些页面也用了国际化，是不是可以全局搜索$t删除，然后把内容替换成想要的语言内容。

对于已有的国际化内容，你可以在页面上删掉$t的，但是也可以去i18n文件里修改翻译，后者会快一点，方便管理一些，新页面可以直接写中文
