### ISSUE TITLE
[代码风格] 建议调整规则允许多行数组或者对象元素最后一个元素加上逗号

### ISSUE THREAD

**Issue by NHZEX** [soybeanjs/soybean-admin#486]
建议`prettier.trailingComma`选项使用默认值`all`，以允许多行数组、对象、参数的最后一个元素加上逗号，这样在追加和修改元素更加方便。

`prettier`的默认规则也是加逗号的：https://prettier.io/docs/en/options.html#trailing-commas

ps：如果项目自行修改规则，后面合并`soybean`容易产生大量差异。

**Comment by honghuangdc** [comment]
这个风格已经延续很久
自己变更配置后代码变更后，后续合并应该影响很小
