### ISSUE TITLE
[Bug]: 对 window 对象扩展的 ts 定义在 webstorm 中无效

### ISSUE THREAD

**Issue by NHZEX** [soybeanjs/soybean-admin#487]
### 软件版本

1.2.2

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

当前的`window.$xxx`定义声明不正确，webstorm 无法解析

### 期望的结果是什么？

正确的声明方式：https://stackoverflow.com/a/59499895/10242420

![image](https://github.com/soybeanjs/soybean-admin/assets/14545600/849bae52-e3c1-4389-8ea3-79689eba9a61)

![image](https://github.com/soybeanjs/soybean-admin/assets/14545600/31081a37-98ca-44a8-ad47-d02af1483e4c)

### 实际的结果是什么？

![image](https://github.com/soybeanjs/soybean-admin/assets/14545600/67a89b5f-e6bf-4051-abec-ffcb17560ee9)

### 补充说明（可选）

```ts
export {};

declare global {
  export interface Window {
    /** NProgress instance */
    NProgress?: import('nprogress').NProgress;
    /** Loading bar instance */
    $loadingBar?: import('naive-ui').LoadingBarProviderInst;
    /** Dialog instance */
    $dialog?: import('naive-ui').DialogProviderInst;
    /** Message instance */
    $message?: import('naive-ui').MessageProviderInst;
    /** Notification instance */
    $notification?: import('naive-ui').NotificationProviderInst;
  }
}
```

**Comment by honghuangdc** [comment]
<img width="729" alt="截屏2024-06-12 20 49 26" src="https://github.com/soybeanjs/soybean-admin/assets/49704545/e041dec1-da06-4539-ab7a-9d399544a4d7">

我这边测试是可以解析到的

**Comment by honghuangdc** [comment]
请保证其他地方没有对window类型进行修改而影响

**Comment by honghuangdc** [comment]
这边建议重新拉取 SoybeanAdmin 试试看

我刚有测试过，declare global {} 这种方式会影响其他的类型，暂时不好直接更改

**Comment by NHZEX** [comment]
> 看图标，你ws的版本应该比较老吧，建议更新最新的，最新的几个版本对vue和ts有较大的支持性改动

WebStorm 2024.1.3 不是老的，我现在再次全新项目试试吧

**Comment by NHZEX** [comment]
![image](https://github.com/soybeanjs/soybean-admin/assets/14545600/d6fdfadb-6dc3-42ae-beba-e18b7f56d82c)
全新项目也能复现。
`$message`没高亮也体现出定义没找到。

**Comment by NHZEX** [comment]
> 我刚有测试过，declare global {} 这种方式会影响其他的类型，暂时不好直接更改

我声明后好像没发现什么副作用，先这样用着了。

> 我这边测试也是可以的，检查一下你的环境吧

有装其他插件？我这里的插件看起来也没什么嫌疑。

![image](https://github.com/soybeanjs/soybean-admin/assets/14545600/8ae7db78-9abe-4d80-8151-af31b9cad52c)

**Comment by NHZEX** [comment]
经过研究后应用的最终方案

`global.d.ts`更改
```ts
export {};

declare global {
  export interface Window {
    /** NProgress instance */
    NProgress?: import('nprogress').NProgress;
    /** Loading bar instance */
    $loadingBar?: import('naive-ui').LoadingBarProviderInst;
    /** Dialog instance */
    $dialog?: import('naive-ui').DialogProviderInst;
    /** Message instance */
    $message?: import('naive-ui').MessageProviderInst;
    /** Notification instance */
    $notification?: import('naive-ui').NotificationProviderInst;
  }

  export interface Document {
    startViewTransition?: (callback: () => Promise<void> | void) => ViewTransition;
  }

  /** Build time of the project */
  export const BUILD_TIME: string;
}

interface ViewTransition {
  ready: Promise<void>;
}
```

`env.d.ts`更改
```
// 从 global.d.ts 迁移
interface ImportMeta {
  readonly env: Env.ImportMeta;
}
```

在`example`分支下执行`typecheck`无错误，`ide`能正确识别类型。

**Comment by honghuangdc** [comment]
可以在下个小版本试试
