### ISSUE TITLE
[Bug]: 菜单标签关闭后退出重登，被关闭的标签又显示出来了

### ISSUE THREAD

**Issue by yeahqiao96** [soybeanjs/soybean-admin#495]
### 软件版本

1.2.2

### 运行环境

MacOS

### 运行架构

AMD64

### 重现步骤

https://github.com/soybeanjs/soybean-admin/assets/93234012/3b6b6ae1-b6ef-4ef7-8870-48451fbb5eb6

### 期望的结果是什么？

菜单标签关闭后退出重登，被关闭的标签不显示

### 实际的结果是什么？

菜单标签关闭后退出重登，被关闭的标签又显示出来了

**Comment by Azir-11** [comment]
复现步骤：
1. 打开多个标签，active首页
2. 刷新页面
3. 关闭其他的标签页
4. 重新登录
