### ISSUE TITLE
[功能]: `useTable`支持自定义`transformer`

### ISSUE THREAD

**Issue by NHZEX** [soybeanjs/soybean-admin#498]
- 添加分页参数重映射功能
- 添加`searchParams`钩子允许重写请求参数
- 暴露`transformer`允许外部重写响应结果

**Comment by Azir-11** [comment]
分页参数重映射是指？

**Comment by NHZEX** [comment]
> 分页参数重映射是指？

对接的接口分页参数输入输出五花八门，与`useTable`内置的声明不一致。有映射可以避免改动对框架改动过多，方便复用。（目前是在`apiFn`从新包装一层转换）

例子：
```js
// query
// page=1&limit=20

// resp
{
    "message": "succeed",
    "code": 0,
    "record": [
     // ...
     ],
    "total": 66,
    "page": {
        "size": 10,
        "current": 1,
        "hasMore": true
    }
}
```

**Comment by beijibeijing** [comment]
columns里能加个checked字段么，直接设置显隐状态。

**Comment by Azir-11** [comment]
> columns里能加个checked字段么，直接设置显隐状态。

这个就不考虑了，不是正常的做法，你要的话自己加就行

**Comment by beijibeijing** [comment]
求个合理思路~
> > columns里能加个checked字段么，直接设置显隐状态。
> 
> 这个就不考虑了，不是正常的做法，你要的话自己加就行

**Comment by honghuangdc** [comment]
待讨论：之前提供的useTable，是每次用到都需要写transformer的，后来考虑后端服务的接口结构都是固定的，所以就根据类型去写了固定的useTable，尽可能的保证使用时参数的最小化

**Comment by NHZEX** [comment]
> 待讨论：之前提供的useTable，是每次用到都需要写transformer的，后来考虑后端服务的接口结构都是固定的，所以就根据类型去写了固定的useTable，尽可能的保证使用时参数的最小化

因为在移植老接口，存在结构不统一的情况，`transformer`固化用起来会不够灵活。

**Comment by honghuangdc** [comment]
这个也待定，有考虑过，不过实现上类型的处理是个大问题

**Comment by honghuangdc** [comment]
暂不考虑
