### ISSUE TITLE
[Bug]: `useTable`搜索联动时没有重置分页`current=1`

### ISSUE THREAD

**Issue by NHZEX** [soybeanjs/soybean-admin#499]
### 软件版本

1.2.3

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

`use-table`于`search`组件用`v-model`直传参数，查询时没去重置 current = 1，导致结果少于当前页码后表格直接无数据。

而且部分接口返回的`current`参数是带修正的，`total`实际分页少于传参`current`会重置为`1`，直接导致页面显示空且当前页为`1`，但实际是`api`查询非第一页。

考虑使用方案：`getData(options?: { resetFirstPage?: boolean })`

### 期望的结果是什么？

应当重置第一页，`demo` 的虚拟数据无法展示这个逻辑。

### 实际的结果是什么？

空白且是虚假的第一页

**Comment by honghuangdc** [comment]
提供一个函数 getDataByPageNum
```ts
function getDataByPage(pageNum: number = 1) {
  updateSearchParams({ current: pageNum });
  getData();
}
```

**Comment by NHZEX** [comment]
> 提供一个函数 getDataByPageNum
> 
> ```ts
> function getDataByPage(pageNum: number = 1) {
>   updateSearchParams({ current: pageNum });
>   getData();
> }
> ```

也可行，没毛病

PS：唯一想到如果有其他没考虑到的场景时会不会导致`getDataByXXX`膨胀问题。
