### ISSUE TITLE
[功能请求] 关于布局导航的新展示形式

### ISSUE THREAD

**Issue by bytegolang** [soybeanjs/soybean-admin#501]
交互形式：一级菜单在头部，子菜单在侧边栏，选择头部菜单 加载侧边栏子集菜单，默认选中第一个菜单中菜单类型为菜单的菜单，若无子菜单，就不展示侧边栏，当一级菜单过多时，展示效果类似标签页，可以鼠标左右滑动，或者加一个更多的按钮，来展示剩下的一级菜单
![d124d20bff6a99483ad0cd74f044903](https://github.com/soybeanjs/soybean-admin/assets/16700482/3f8d1ff0-9e31-4d12-9960-5286060bb133)

**Comment by honghuangdc** [comment]
同 #365
