### ISSUE TITLE
[功能]: 添加`vite.css.modules`支持WebStorm推导

### ISSUE THREAD

**Issue by NHZEX** [soybeanjs/soybean-admin#502]
设置一下默认参数，让`css modules`导入后的自动兼容驼峰命名，将直接兼容`IDE`推导，不需要再维护额外的`ts`定义。

```ts
css: {
  modules: {
    localsConvention: 'camelCase',
    scopeBehaviour: 'local',
  }
}
```

**Comment by honghuangdc** [comment]
又是 WebStorm的问题？

**Comment by NHZEX** [comment]
> 又是 WebStorm的问题？

不是IDE有问题，是IDE是支持驼峰命名的类型推断，刚好可以利用上，这不用维护`d.ts`了。
不够`vscode`是否支持我没尝试过。

![image](https://github.com/soybeanjs/soybean-admin/assets/14545600/3a1920e9-c1a6-454e-9228-065d2c679977)

打印 style 对象  
![image](https://github.com/soybeanjs/soybean-admin/assets/14545600/1988c4e1-041e-440c-868f-17f003269d3a)

**Comment by honghuangdc** [comment]
项目里面 `packages/materials/src/libs/admin-layout/index.vue`的css modules写法 目前用的是 `typed-css-modules` 依赖，结合VSCode插件 [CSS Module Typed
](https://marketplace.visualstudio.com/items?itemName=awwit.typed-css-modules-plugin) ，编写了css后会自动生成 .d.ts 文件，不需要手动维护

**Comment by NHZEX** [comment]
嗯，驼峰样式主要调用起来少写`[‘’]`几个符号，代码看起来简约些，`WebStorm`是原生支持了。

可以考虑启用，也没有副作用。

**Comment by honghuangdc** [comment]
这个得待定，因为项目本身不推荐采用css modules的写法，packages/materials里面用到了是因为早期是独立的依赖包，用了css modules 写法，迁移过来后就没有改，应该推荐用unocss的写法。

**Comment by NHZEX** [comment]
> 这个得待定，因为项目本身不推荐采用css modules的写法，packages/materials里面用到了是因为早期是独立的依赖包，用了css modules 写法，迁移过来后就没有改，应该推荐用unocss的写法。

嗯，因为在使用`tsx`自定义组件，没想到有比`css modules`更好的方法去应用预设好的样式。
