### ISSUE TITLE
element-plus版本意愿调查

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin#505]
鉴于有些开发选择element-plus版本，同时考虑作者维护多个UI版本的巨大工作量，为此想调查下能够接受付费制的element-plus版本，版本功能和naive-ui的保持一致：

——

1. 费用299（一次性的代码，支持后续的bug修复）
2. 费用499（支持后续新版本的更新与升级）
3. 费用699（支持后续新版本的更新与升级，支持售后服务群，免费回答和框架相关的问题）

——

有意愿的可以登记下，留个计数，统计时间截止到本周五

1. 费用选项(1|2|3), 昵称 XXX（昵称可省略）
2. 
3.

**Comment by LoveGT** [comment]
1. 费用选项(3) 昵称: gaoao9527

**Comment by honghuangdc** [comment]
经过意向收集，决定不做element-plus版本
