### ISSUE TITLE
[功能]: Request请求处理后端Code时阻塞后续业务代码

### ISSUE THREAD

**Issue by majinkai** [soybeanjs/soybean-admin#506]
### 描述

VITE_SERVICE_LOGOUT_CODES=8888,8889

8888,9999：跳转登录页面，且阻塞后续代码执行

VITE_SERVICE_MODAL_LOGOUT_CODES=7777,7778

7777,7778：弹出模态窗口并阻塞后续代码，点击OK跳转登录页面，点击取消执行后续代码

### 建议的解决方案

同上

**Comment by Azir-11** [comment]
阻塞代码并不是一个很好的提议，一般在api调用的时候建议同时取出data和error，手动执行
```
if (error)
  return
```
此时阻塞与否也就没什么意义了，倘若是调用者本身没有去处理error的情况，我会认为这是个人原因导致的，应该规范自己的写法

**Comment by majinkai** [comment]
这两个特殊的code，应该阻塞代码，因为代码执行的是注销步骤，后续业务代码并不需要执行，否则会导致各种报错，应当从框架层面去尽可能避免报错

**Comment by honghuangdc** [comment]
对每个请求进行错误判断即可
