### ISSUE TITLE
[功能]: 增加后端接口无权限code对应的处理逻辑

### ISSUE THREAD

**Issue by majinkai** [soybeanjs/soybean-admin#508]
### 描述

后端请求也会经常性的出现权限不足的情况，应当与之对应code特殊处理，提示用户没有权限，不注销当前登录状态

### 建议的解决方案

VITE_SERVICE_NO_PERMISSION_CODES=4444,4445

**Comment by Azir-11** [comment]
这个处理逻辑指的是跳转到403页面吗？

**Comment by honghuangdc** [comment]
系统默认会有请求错误的提示，后端直接返回没有权限的错误信息即可
