### ISSUE TITLE
[功能]: 允许每个页面独立定制 Layout Footer 的内容

### ISSUE THREAD

**Issue by NHZEX** [soybeanjs/soybean-admin#515]
### 描述

当前在单一页面下视乎没法控制`footer`，只能全局控制是否显示。是否能让每个页面能自行控制`footer`显示的内容？

### 建议的解决方案

例如这种：https://d2.pub/doc/d2-admin/component/container.html#%E6%A8%A1%E5%BC%8F-card  里提到的方法
```vue
<template>
  <d2-container type="card">
    <template slot="header">Header</template>
    <d2-demo-article/>
    <template slot="footer">Footer</template>
  </d2-container>
</template>
```

**Comment by honghuangdc** [comment]
base-layout本身就是针对多个页面应用的同一个布局组件，想要不同页面显示不同的底部，可以这样去实现
在base-layout里面拿到当前路由进行控制，如果想要控制展示和隐藏，可以在路由里面配置一个参数hideFooter，然后再绑定到base-layout中，如果想自定义不同的内容，根据不同路由渲染不同内容即可

**Comment by NHZEX** [comment]
大致明白思路了，考虑框架层面去更方便的集成么？

**Comment by honghuangdc** [comment]
暂时不考虑
