### ISSUE TITLE
[Bug]: 关于自动生成的elegant跟用户定义的静态路由冲突导致页面布局错乱

### ISSUE THREAD

**Issue by yyahaowan** [soybeanjs/soybean-admin#517]
### 软件版本

v20.13.1

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 重现步骤

step1 : 删除 src/elegant 目录
step2: pnpm run dev 重新生成该目录及内容
step3: 服务器启动打开登录页面布局是不对的

### 期望的结果是什么？

静态路由使用 blank布局
<img width="1196" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/23733392/4d503fe7-c91f-4f5a-b24b-6ec1290f2f8a">

### 实际的结果是什么？

静态路由使用 base 布局

<img width="1395" alt="image" src="https://github.com/soybeanjs/soybean-admin/assets/23733392/43bab000-900d-40f8-b83b-b3ce73fd2a22">

**Comment by Azir-11** [comment]
可以在插件里配置一下，login生成的layout

**Comment by yyahaowan** [comment]
是的，目前是这么解决的，谢谢~

**Comment by honghuangdc** [comment]
由于插件没有记录旧的路由数据作为备份，所以当路由数据被删掉后，只能默认选择一个布局组件，再对路由数据进行变更。
可以在 [ElegantRoute](https://github.com/soybeanjs/elegant-router)这里提个需求

**Comment by honghuangdc** [comment]
[计划](https://github.com/soybeanjs/elegant-router/issues/25)

**Comment by cheen77** [comment]
> 可以在插件里配置一下，login生成的layout

怎么配置呢
