### ISSUE TITLE
[功能]: main分支精简，只保留首页菜单

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin#518]
### 描述

为了方便各位开发方便合并，现将main分支的代码进行精简，只保留首页这个菜单，其余的放到example分支进行维护

### 建议的解决方案

main分支精简代码

**Comment by haitang1894** [comment]
不太好,感觉可以分出来一个分支,只保留首页,主分支还是保持这样

**Comment by Azir-11** [comment]
> 不太好,感觉可以分出来一个分支,只保留首页,主分支还是保持这样

没问题的，我们是在main分支加了这些管理之后才决定的把其他页面迁移到example，把main当成精简分支，所以这几个页面一直都是多出来的，只是没有人提就没管，刚好今天有小伙伴说这几个页面对他的更新造成了困扰，就正好去掉了

**Comment by haitang1894** [comment]
> > > 不太好,感觉可以分出来一个分支,只保留首页,主分支还是保持这样
> > 
> > 
> > 没问题的，我们是在main分支加了这些管理之后才决定的把其他页面迁移到example，把main当成精简分支，所以这几个页面一直都是多出来的，只是没有人提就没管，刚好今天有小伙伴说这几个页面对他的更新造成了困扰，就正好去掉了
> 
> 保留main分支现有结构会好点。很多人拉代码都是不带分支的，默认main，那运行起来看到空空如也就很奇怪。精简分支，相信更新的也不会多。建议单开。

对, 我觉得也是这样，能研究项目的自己就可以删掉多的代码。不看项目就想着自己直接上来就用，后续群里问问题的肯定也会增加。

**Comment by myderr** [comment]
可以顺便标注一下文件夹的属性吗，
比如 xx文件夹可以随便修改
xx文件夹 尽量少更改
xx文件夹无特殊需求尽量别动
这样想我这样初次接手的知道什么可以动，什么不可以动，
而且这样也方便后续升级了，直接git拉去也不会冲突

**Comment by Azir-11** [comment]
> 可以顺便标注一下文件夹的属性吗， 比如 xx文件夹可以随便修改 xx文件夹 尽量少更改 xx文件夹无特殊需求尽量别动 这样想我这样初次接手的知道什么可以动，什么不可以动， 而且这样也方便后续升级了，直接git拉去也不会冲突

开始开发了一般都会有冲突的，也不存在什么随便改的东西，只要和我们的代码不一样那就是有冲突需要解决的，建议就是代码注释写清楚，这样你自己解决起来也方便，特别是对于原本逻辑的变更这类的，比如路由守卫等部分内容，熟悉系统之后会好很多

**Comment by myderr** [comment]
> > 可以顺便标注一下文件夹的属性吗， 比如 xx文件夹可以随便修改 xx文件夹 尽量少更改 xx文件夹无特殊需求尽量别动 这样想我这样初次接手的知道什么可以动，什么不可以动， 而且这样也方便后续升级了，直接git拉去也不会冲突
> 
> 开始开发了一般都会有冲突的，也不存在什么随便改的东西，只要和我们的代码不一样那就是有冲突需要解决的，建议就是代码注释写清楚，这样你自己解决起来也方便，特别是对于原本逻辑的变更这类的，比如路由守卫等部分内容，熟悉系统之后会好很多

感谢回复，其实也不是想随便乱改什么，只是前期对整体不了解，只是怕为了实现功能而动到一些不该动的文件了

**Comment by qq3079353653** [comment]
有关table的是否也能删除？因为这个其实和系统也没太大的关系，本质还是属于大佬提供的业务组件。

**Comment by Azir-11** [comment]
> 有关table的是否也能删除？因为这个其实和系统也没太大的关系，本质还是属于大佬提供的业务组件。

use-table是项目提供的hook，是结合了ts和项目其他部分功能的列表页解决方案，有列表页的都建议可以一用，这个就不删了，除非说项目里没有列表。

**Comment by qq3079353653** [comment]
请看这个需求是否合理：编辑列表数据时，打开表单界面，实际业务员一般都是从后台请求数据的，但是该功能是从列表拿数。 并且ID也限制死了 必须是“ID”， 有一定的限制性。

**Comment by Azir-11** [comment]
> 请看这个需求是否合理：编辑列表数据时，打开表单界面，实际业务员一般都是从后台请求数据的，但是该功能是从列表拿数。 并且ID也限制死了 必须是“ID”， 有一定的限制性。

1. 你需要明白示例是什么意思：
示例[shì lì]
示例，汉语词语，拼音是shì lì，意思是带有展示、列举之意；例，是例子、案例的意思，示例：列举、展示出典型的案例、例子已做**参照**。
代码是在你手上的，页面内的操作逻辑应该由你自己判断并书写。
2. 请不要在该issue内讨论无关问题

**Comment by qq3079353653** [comment]
解决这个问题需要修改hook，此时会导致合并的复杂度。所以个人觉得，将其移出精简版有一定的合理性。

**Comment by Azir-11** [comment]
> 解决这个问题需要修改hook，此时会导致合并的复杂度。所以个人觉得，将其移出精简版有一定的合理性。

这个问题是页面的，不是hook的
