### ISSUE TITLE
[Bug]: 不知道是不是bug

### ISSUE THREAD

**Issue by zjbdiy** [soybeanjs/soybean-admin#521]
### 软件版本

最新

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

我前端并不精通,也是第一次使用此框架, 我查看了源码,尝试理解了proxy相关逻辑
整体逻辑就是创建了两个开发代理 proxy-default,proxy-demo
然后由request实例的baseurl对所有请求添加了前缀,使得开发代理能够匹配
我无法理解这个做法,这不是正常的代理逻辑,代理应与业务无关,且没有侵入性

而且存在严重bug,即请求不是request,则无法代理

假设存在标签 <a href='/file/download?filename=test.zip&accesscode=xxxx' download>下载<a>
则此请求将始终失败

### 期望的结果是什么？

能代理所有请求

### 实际的结果是什么？

不属于request的请求,无法代理

**Comment by zjbdiy** [comment]
`<a href='/file/download?filename=test.zip&accesscode=xxxx' download>下载</a>`

**Comment by honghuangdc** [comment]
你这个下载的写法本身就是错误的
