### ISSUE TITLE
[Bug]: git commit 提交自动删除某些代码文件

### ISSUE THREAD

**Issue by hrbrobin** [soybeanjs/soybean-admin#526]
### 软件版本

latest

### 运行环境

MacOS

### 运行架构

None

### 重现步骤

开发完需求后，执行git commit，会触发:
"simple-git-hooks": {
    "commit-msg": "pnpm sa git-commit-verify",
    "pre-commit": "pnpm typecheck"
  },
  在检查过程中会自动删除我的代码文件，不知道是什么原因导致的，不符合规范的文件会自动删除吗？有没有配置可以去掉自动删除代码文件的

### 期望的结果是什么？

修复bug或者是配置支持不自动删除临时代码文件

### 实际的结果是什么？

目前是把我写过的vue代码文件自动删除了

**Comment by Azir-11** [comment]
是否可提供一下稍微具体一点的复现步骤？

**Comment by hrbrobin** [comment]
复现不了哦，偶尔出现的，好几个人出现了；但是却不知道怎么复现；
步骤：
1.正常开发需求，新建vue文件，然后写代码
2.执行git commit操作后，如果有相应的类型报错或者是其他eslint校验报错，会提交不了，然后发现代码文件被删了，打印的日志中出现“cleaning temporary files...”等信息

**Comment by honghuangdc** [comment]
去simple-git-hooks去找一下相关问题

**Comment by honghuangdc** [comment]
文件会被暂存的，相当于执行了git stash
