### ISSUE TITLE
[功能]: 菜单栏的展开项在`Tabs`激活项变化后仍能保持住

### ISSUE THREAD

**Issue by NHZEX** [soybeanjs/soybean-admin#528]
### 描述

菜单栏与`Tabs`的活动`Tab`联动时会导致菜单展开项全部被折叠，只会保留当前`Tab`。

### 建议的解决方案

需求支持保持当前展开状下在去展开当前活动`Tab`的菜单项。

并支持把焦点滚动到要激活的菜单项（这个在展开长菜单后能优化体验）

### 替代方案

支持使用`menuInstRef.value?.showOption(key)`方式展开菜单项

**Comment by NHZEX** [comment]
> 菜单栏的展开与tab的滚动都可以认为是正在查找某个菜单，跳转页面则是已经找到了目标，在此时收起其他的无关项是正常的，同时这也隐性的支持了快速收起菜单的功能。

嗯，提到内容很切入要点。

当前主要遇到问题就是同时跨多个模块开发，有时候反复切换Tab时发现菜单栏一直重置收起，导致需要展开菜单的情况。
同时也想到实际操作时会存在导航菜单深和跨模块频繁切换的情况，当`Tabs`保持打开多个选项卡后要找到需要的选项是存在一定困难的（浏览器就经常遇到），这时候通过菜单切换又会存在反复展开的困扰。

**Comment by honghuangdc** [comment]
SoybeanAdmin更多的是站在普通用户的角度而设计的，遵循大多数使用者的习惯。而不是让系统去适应向楼主提到的在开发过程中遇到的问题，包括之前楼主提的一些issues(标题区分测试、生产等)都是个人使用习惯的问题，这些功能如果想实现，可以去变更逻辑实现定制化。
