### ISSUE TITLE
[功能]: 在 Tabs 组件页面触发刷新按钮时能实现一个通知事件

### ISSUE THREAD

**Issue by NHZEX** [soybeanjs/soybean-admin#531]
### 描述

![image](https://github.com/soybeanjs/soybean-admin/assets/14545600/cab59781-345d-4048-bef8-bc7cd032fae3)

举个场景：当前页面在上传大文件时，有人点一下刷新页面按钮，上传请求是没法主动取消，刷新事件也没办法阻止，导致请求与组件上下文脱钩了。

### 建议的解决方案

useTabStore 提供一个事件订阅的方法。（可能得实现每个 Tab 独立上下文更好？当前好像没这个概念）

**Comment by honghuangdc** [comment]
一般上传文件都是做成全局的，取消上传是需要用户去主动确认的。
你这里想做成上传只在当前页面有效，可以遵循vue的组件生命周期即可，如果是缓存页面，就在 `onDeactivated`里，非缓存页面，在`onBeforeUnmount`里

**Comment by NHZEX** [comment]
> 一般上传文件都是做成全局的，取消上传是需要用户去主动确认的。 你这里想做成上传只在当前页面有效，可以遵循vue的组件生命周期即可，如果是缓存页面，就在 `onDeactivated`里，非缓存页面，在`onBeforeUnmount`里

当前确实是上传做在单个页面生命周期内，而且页面启用了`keepAlive`，问题在于`onActivated`和`onDeactivated`这组事件连切换`Tab`都会触发，没法用于处理上传中止。

**Comment by honghuangdc** [comment]
> > 一般上传文件都是做成全局的，取消上传是需要用户去主动确认的。 你这里想做成上传只在当前页面有效，可以遵循vue的组件生命周期即可，如果是缓存页面，就在 `onDeactivated`里，非缓存页面，在`onBeforeUnmount`里
> 
> 当前确实是上传做在单个页面生命周期内，而且页面启用了`keepAlive`，问题在于`onActivated`和`onDeactivated`这组事件连切换`Tab`都会触发，没法用于处理上传中止。

那你自行基于mitt在tab store加个事件
