### ISSUE TITLE
[功能]: @sa/axios: 使用AbortController替换AbortController

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin#532]
### 描述

在axios v0.22.0起，`CancelToken`已被废弃，现在使用`AbortController`进行替换

### 建议的解决方案

使用`AbortController`进行替换

### 额外的上下文

基于`CancelToken`实现的取消请求是通过给每个请求生成唯一的请求id，供全局去调用，但是无法支持单个请求去控制，现使用`AbortController`需支持

**Comment by NHZEX** [comment]
是打算放弃`cancelRequest`与`cancelAllRequest` 方法，还是放弃使用`requestId`去取消的实现？

**Comment by honghuangdc** [comment]
这两个方法仍然会保留
