### ISSUE TITLE
[功能]: 关于fetchHook

### ISSUE THREAD

**Issue by ALosee** [soybeanjs/soybean-admin#533]
### 描述

有想过把useHookTable的中的处理apifn的逻辑提取成一个useHookFetch，相关的loading、empty状态放在hookFetch中做，这样是不是会更好一点，useHookFetch也能是一个通用的fetchhook

- [ ] 

### 建议的解决方案

hookFetch

**Comment by Azir-11** [comment]
1. useTable的其实没什么必要再继续拆了，在哪做都是要做的，拆了反而东一块西一块
2. 类似useFetch这种东西可以考虑，传入apiFn，然后返回一些响应式的变量，但是因为flatRequest的原因，data不能直接取用，先看看社区里对这类hook的需求大不大吧
