### ISSUE TITLE
[功能]: 使用presetAttributify优化项目的过长类名

### ISSUE THREAD

**Issue by Azir-11** [soybeanjs/soybean-admin#558]
### 描述

在使用原子css开发的过程中，不可避免的会遇到类名过长的问题，虽然现在已经支持了类名排序，但是在大段的类名中阅读、寻找等仍然是一件比较麻烦的事情，注意到unocss有一个官方预设：Attributify，它似乎能解决这个问题，并使得原子的写法更容易能被人接受、更优雅。
相关文档：https://unocss-cn.pages.dev/presets/attributify

### 建议的解决方案

引入 `presetAttributify ` 预设，对项目内已(可能)有的过长类名做优化处理

**Comment by honghuangdc** [comment]
名称过长可以考虑使用一些内置指令去解决 https://unocss.dev/transformers/directives#at-apply

我的想法是组件属性和class类名最好不要混在一起
