### ISSUE TITLE
[Bug]: 登录过期窗口弹出两次

### ISSUE THREAD

**Issue by 15317668327** [soybeanjs/soybean-admin#565]
### 软件版本

1.3.0

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

在后端登录状态已过期的前提下，点击某个路由，该路由页面打开时就会初始化调用两个不同的后端接口，由于登录状态已经过期，返回告知了前端已过期，弹出了登录过期弹出框，但是弹出了两次

### 期望的结果是什么？

在第一个请求到达后端时后端响应返回已过期时前端收到就不再进行第二次请求了，不弹出两个登录过期窗口

### 实际的结果是什么？

弹出了两个登录过期窗口，两次请求都到了后台

### 补充说明（可选）

https://github.com/user-attachments/assets/f64187fb-7971-4471-ad66-62b175230c78

**Comment by xibaoer** [comment]
信已收到！！莫急~~莫急哦  嘿嘿
