### ISSUE TITLE
[功能]: 是否有动态路由或者动态菜单的 demo 

### ISSUE THREAD

**Issue by baiwumm** [soybeanjs/soybean-admin#566]
### 描述

非常感谢作者的开源，我想问一下有人做过动态路由或者动态菜单的功能吗，是否有 demo 或者代码参考

### 建议的解决方案

感谢

**Comment by Azir-11** [comment]
env里面把 `VITE_AUTH_ROUTE_MODE` 改成 `dynamic` 就是动态路由了，详情参考文档 https://docs.soybeanjs.cn/guide/router/dynamic.html
