### ISSUE TITLE
[功能]: 演示页面的插件有实际代码参考吗？

### ISSUE THREAD

**Issue by symbolChai** [soybeanjs/soybean-admin#576]
### 描述

比如地图、条形码、剪切板等插件, 有实际代码或者插件说名参考吗？

### 建议的解决方案

网址或实际代码

**Comment by symbolChai** [comment]
我是在gitee里拉的代码 没有example分支

**Comment by Azir-11** [comment]
gitee的更新是不定期的，建议有能力还是在github拉取

**Comment by symbolChai** [comment]
> gitee的更新是不定期的，建议有能力还是在github拉取

我知道了, 我用的是ant的版本的仓库

**Comment by symbolChai** [comment]
> > > gitee的更新是不定期的，建议有能力还是在github拉取
> > 
> > 
> > 我知道了, 我用的是ant的版本的仓库
> 
> 额，你另外个issues提的bug也是antd版本的。我看naive版本看半天

抱歉, 我也才发现,

**Comment by Azir-11** [comment]
> > gitee的更新是不定期的，建议有能力还是在github拉取
> 
> 我知道了, 我用的是ant的版本的仓库

这个不关事的，这些插件不依赖于特定框架，可以直接看，现在人手不是很足，antdv版本的不一定什么时候会更新
