### ISSUE TITLE
混合菜单跳转问题

### ISSUE THREAD

**Issue by RanMaoting** [soybeanjs/soybean-admin#577]
这个功能似乎有点问题,在这个模式下点击一级菜单不会自动跳转到下面的子菜单,有点违反直觉

_Originally posted by @RanMaoting in https://github.com/soybeanjs/soybean-admin/issues/574#issuecomment-2264427654_

**Comment by Azir-11** [comment]
你的意思是点击菜单之后自动进入当前点击菜单的第一个子菜单吗？

**Comment by RanMaoting** [comment]
抱歉, 我似乎有点搞乱了,我在这个问题下重新贴一下问题

现在点击一级菜单并不会跳转,只会展开侧边栏,从操作习惯上来说默认进入第一个子菜单是否会好点
或者说在离开后能在再次点击一级菜单时能够进入上次在这个菜单下的最后一个菜单,这样的话感觉操作是连续的,只是不知道实现起来是否有难度

**Comment by honghuangdc** [comment]
https://fantastic-admin.github.io/pro-example/#/home
https://www.vben.pro

上述的管理系统的这个布局都是不会直接跳转子菜单的

**Comment by honghuangdc** [comment]
从逻辑上讲，点击顶部菜单后，如果有子菜单，不跳转也没啥问题，如果你想实现第一个子菜单跳转可以自行改一下逻辑

**Comment by Azir-11** [comment]
你这种思路会有个问题，可能会产生无谓的跳转，比如：
1. 我的目标是找到某个菜单，我需要进各个菜单查看子菜单
2. 我需要进入这个菜单下的除第一个和上次进入那个的其他菜单

在此类非常常见情况下，很可能会发生不必要的跳转，所以没必要加，导航到上一个进入过的菜单用tab就好了

**Comment by RanMaoting** [comment]
ok, 感谢回复
