### ISSUE TITLE
[功能]: 考虑`Prettier`的替代方案

### ISSUE THREAD

**Issue by NHZEX** [soybeanjs/soybean-admin#586]
### 描述

遇到的痛点基本上这篇文章都提到了：https://antfu.me/posts/why-not-prettier-zh

我经常遇到的问题
1. 没有启用尾随逗号，这个之前提过了，但我觉得答案并不能解决问题，因为更改默认设置后全部代码都会被重写格式化，当项目合并SA的上游更新容易产生很大不必要的噪音。https://github.com/soybeanjs/soybean-admin/issues/486
2. 还要一个目前无解的问题，代码有时多一个字母少一个符号就给你反复展开合并对象或者参数列表，产生很多不必要的变更噪音，只能`// prettier-ignore`添加妥协了。这个很影响可读性和代码合并。

关于为什么不自己替换方案的问题：因为我还要定期跟踪`SA`的上游更新，如果我自行更改代码风格可以参考`antfu`的文章的副作用例子，就代码展开或者内联是不可控这一个点，就会导致大量的无意义差异，合并会只会越来越困难。目前只能选择妥协。

### 建议的解决方案

比如文章内提到的`@antfu/eslint-config`加上SA专有的风格定制化配置。

**Comment by honghuangdc** [comment]
代码风格这个只能跟着当前项目的配置，如果想自己定义新的配置，肯定会对合并代码带来影响，目前没有啥好的解决方案。就算用@antfu/eslint-config也没法解决，只要自己fork的项目风格和本项目的不一致，问题就一直在。
而且每个人的风格又不一样，不就可能让上游去向下兼容。
