### ISSUE TITLE
[功能]: n-modal组件拖拽、全屏功能有计划吗？

### ISSUE THREAD

**Issue by xhs101** [soybeanjs/soybean-admin#596]
### 描述

n-modal组件拖拽、全屏功能
![Uploading 图片.png…]()

### 建议的解决方案

n-modal组件拖拽、全屏功能

**Comment by Azir-11** [comment]
去naive-ui的组件库里寻找解决方案，已经有参考的实现了

https://github.com/tusen-ai/naive-ui/issues/5501
