### ISSUE TITLE
[Bug]: 【移动端】列表左右滑动失效

### ISSUE THREAD

**Issue by PT600** [soybeanjs/soybean-admin#602]
### 软件版本

1.3.4

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

1. 在手机端使用管理员进入系统
2. 进入系统管理/用户管理模块
3. 左右滑动用户列表页面

### 期望的结果是什么？

用户列表页面能左右滑动

### 实际的结果是什么？

Tab的前进后退

**Comment by Azir-11** [comment]
在表格区域左右滑动的时候是正常的，未能复现tab的前进后退，可否提供详细点的说明或是录屏？

**Comment by Azir-11** [comment]
你滑动的区域在哪里？tab栏本身是支持左右滑动的

**Comment by PT600** [comment]
是在表格区域滑动。详细步骤：
1. 第一次在表格区滑动是正常的，
2. 然后在表格外滑动，能触发tab的前进和后退，
3. 然后表格区就不能滑动了

浏览器是红米手机自带的

**Comment by Azir-11** [comment]
测试过了，左右滑动进行前进后退是浏览器行为，和页面无关，不会修复

**Comment by PT600** [comment]
我也发现了，谢谢
