### ISSUE TITLE
[功能]: 希望新增一个配置tab栏全屏不显示tab栏，只显示内容

### ISSUE THREAD

**Issue by ashuicoder** [soybeanjs/soybean-admin#603]
### 描述

一般情况下，全屏的场景大部分都是希望只看到内容，目前的内容全屏包括着tab栏，全屏内容不美观

### 建议的解决方案

新增一个配置

**Comment by honghuangdc** [comment]
这个可以在全屏触发的时候把 tab.visible 设置为false

需求不常见，自行定制化变更即可
