### ISSUE TITLE
[Bug]: 左侧菜单混合模式收缩菜单时二级菜单显示异常

### ISSUE THREAD

**Issue by Azir-11** [soybeanjs/soybean-admin#608]
### 软件版本

1.3.4

### 运行环境

MacOS

### 运行架构

None

### 重现步骤

1. 启用左侧菜单混合模式
2. 在左下角收缩菜单
3. 打开任意一个菜单

<img width="365" alt="image" src="https://github.com/user-attachments/assets/5b70f692-6e89-47fe-8425-7633aaf0b67a">

### 期望的结果是什么？

二级菜单正常显示

### 实际的结果是什么？

二级菜单也保持了收缩模式

**Comment by mufeng889** [comment]
![Uploading 7f80ce337461f5beeb2ad1f98ba0914.png…]()
