### ISSUE TITLE
原生的checkBox 显示纯黑

### ISSUE THREAD

**Issue by duxubo** [soybeanjs/soybean-admin#614]
### 描述

![image](https://github.com/user-attachments/assets/a2978abd-4a76-4f80-9c31-2f4248fcc180)

### 建议的解决方案

请求 解决方案

**Comment by Azir-11** [comment]
请使用issue模板提bug：https://github.com/soybeanjs/soybean-admin/issues/new?assignees=&labels=bug%3F&projects=&template=bug-report_cn.yaml&title=%5BBug%5D%3A+

并将相关代码以及复现步骤补充完整
