### ISSUE TITLE
[Bug]: 原生html checkBox 显示纯黑

### ISSUE THREAD

**Issue by duxubo** [soybeanjs/soybean-admin#615]
### 软件版本

1.3.4

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

<template>
    
    <div>
        <input type="checkbox" v-model="email" />
    </div> 

    <NCard>
        <input type="checkbox"  />
    </NCard>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const email = ref('')   

</script>
 

### 期望的结果是什么？

正常显示

### 实际的结果是什么？

![image](https://github.com/user-attachments/assets/0fe32462-1f3b-4f6c-8f73-a801526c4aa4)

**Comment by honghuangdc** [comment]
未复现，自己排查下是不是引入了一些额外的样式导致的

**Comment by duxubo** [comment]
你好 我直接用 你的线上地址，在控制台用js 添加一个checkbox 是纯黑的哦
![image](https://github.com/user-attachments/assets/88693073-95e6-4037-a5b6-051bc6e926cd)

![image](https://github.com/user-attachments/assets/34c50bdc-65b1-4ffe-a0f4-7767dbbe7661)

// 创建一个新的复选框
var checkbox = document.createElement('input');
checkbox.type = 'checkbox';
checkbox.name = 'myCheckbox';
checkbox.value = 'Value';
checkbox.id = 'myCheckboxId';
 
// 设置一些可选属性
checkbox.checked = true; // 设置默认选中状态
checkbox.disabled = false; // 设置是否禁用复选框
 
// 设置点击事件处理程序（可选）
checkbox.onclick = function() {
  alert('Checkbox is ' + (this.checked ? 'checked' : 'unchecked'));
};
 
// 将复选框添加到页面的某个部分
document.body.appendChild(checkbox);
<input type=​"checkbox" name=​"myCheckbox" value=​"Value" id=​"myCheckboxId">​

**Comment by Azir-11** [comment]
> 你好 我直接用 你的线上地址，在控制台用js 添加一个checkbox 是纯黑的哦 !

那应该是你的浏览器问题，我这里线上环境和dev环境试过都是正常的
<img width="1953" alt="image" src="https://github.com/user-attachments/assets/e9578825-ee13-4194-87d9-aa17066d6012">

**Comment by duxubo** [comment]
![image](https://github.com/user-attachments/assets/91603066-68ee-41d8-9d65-97e3275f3d74)
我找到原因了是因为的win11电脑 默认暗黑模式，但是前端的主题不是暗黑模式啊，不用这个模式就可以正常显示  
请问这个能处理吗

**Comment by Azir-11** [comment]
主体配置里有个主体模式，

**Comment by honghuangdc** [comment]
原生的需要自行适配
