### ISSUE TITLE
[功能]: 为什么设置了keepAlive但是没起效果呢？

### ISSUE THREAD

**Issue by mxian** [soybeanjs/soybean-admin#616]
### 描述

**routes.ts设置了keepAlive：**

![image](https://github.com/user-attachments/assets/51f9f09a-2008-4a83-aebf-911ba980558b)

**页面：**
![image](https://github.com/user-attachments/assets/100c5014-6237-41cf-9efb-817bfc3c7fb4)

### 建议的解决方案

**我在页面上输入了一些文字后，切换tab，再回来，页面数据没有缓存，是不是我哪里设置的不对呢？**

**Comment by honghuangdc** [comment]
得用setup的写法，或者设置组件名称为路由名称才生效

**Comment by Azir-11** [comment]
用script setup语法糖
