### ISSUE TITLE
[功能]: 提供没有国际化的方案

### ISSUE THREAD

**Issue by Suomm** [soybeanjs/soybean-admin#619]
### 描述

项目只有中文一种语言，不需要做国际化处理，现在默认是内置国际化，这样所有的提示词，像：`操作（action）`，`新增（add）` 等等使用的时候都是键值，不直观。

### 建议的解决方案

提供一个分支去掉国际化适配。

**Comment by Azir-11** [comment]
维护成本过高，目前没有足够精力，不考虑了
你在后续使用的时候可以直接写中文，不使用i18n
