### ISSUE TITLE
[功能]: 当路由父级的子项被动态过滤为空时，父级支持自动隐藏

### ISSUE THREAD

**Issue by NHZEX** [soybeanjs/soybean-admin#621]
### 描述

图中为为`系统管理`的子级都被被权限过滤为空，且父级没有声明任何权限控制
![image](https://github.com/user-attachments/assets/a5c78b7f-6f5c-4bae-b646-6e7b58b862aa)

给父级去定定义权限可以解决，但如果每个子机的权限都需要同时在父级声明维护这个操作不友好，容易发生错漏。

### 建议的解决方案

当权限路由声明了`children`且同时为空数组时，无论父级是否有权限都会被自动被过滤

**Comment by mufeng889** [comment]
这个我觉的不是前端的事情 ，应该是后端没有处理好  ，在动态添加路由的时候还是会被添加上 ，前端总不可能判断是否有children从而决定要不要把这个路由添加上吧，就算在侧边栏被过滤了   路由依然存在  这并不能算是前端的问题吧
