### ISSUE TITLE
[疑问]: 能否将本后台管理面板集成到同一个前端里

### ISSUE THREAD

**Issue by 1834423612** [soybeanjs/soybean-admin#623]
### 描述

请问一下我目前已经有了一个前端的项目（vite+vue+typescript），基本和本项目同架构。目前想在项目增加一个管理界面，不想配置两个系统，想整合为一个，默认进入前端，后台全局使用/admin进入。请问这个可以实现吗？谢谢

### 建议的解决方案

同个项目文件内，
访问 `/` 默认跳转前端
访问 `/admin` 默认跳转本后台

谢谢

**Comment by Azir-11** [comment]
你开发是想按一个项目开发还是两个？按两个项目开发的话，你在我们系统的.env文件配置一下VITE_BASE_URL为/admin，部署后NGINX配置一下代理，把/admin的请求转发到这个项目就行了

**Comment by 1834423612** [comment]
> 你开发是想按一个项目开发还是两个？按两个项目开发的话，你在我们系统的.env文件配置一下VITE_BASE_URL为/admin，部署后NGINX配置一下代理，把/admin的请求转发到这个项目就行了

是想把两个项目合并为一个，因为分别部署两个项目的话有些麻烦，所以想简便一些。
谢谢

**Comment by Azir-11** [comment]
不知道另一个项目什么情况，直接和没什么办法，除非是按照我们系统的逻辑把页面搬运过来

**Comment by honghuangdc** [comment]
两个项目和成一个还是需要考虑很多因素的，不建议这么做，可以考虑放在一个仓库共享部份代码。
