### ISSUE TITLE
[Bug]: Tab切换在ipad下无法切换，无法关闭

### ISSUE THREAD

**Issue by Chord-Labs** [soybeanjs/soybean-admin#624]
### 软件版本

1.3.4

### 运行环境

MacOS

### 运行架构

None

### 重现步骤

1. 在手机端使用管理员进入系统
2. 打开多个标签
3. 点击切换头部标签

### 期望的结果是什么？

可以正常切换标签

### 实际的结果是什么？

无法切换标签

**Comment by Chord-Labs** [comment]
可点击区域有点小

**Comment by Azir-11** [comment]
有没有图啊，这描述的有点不太好理解

**Comment by Chord-Labs** [comment]
https://github.com/user-attachments/assets/8e1fe551-db8c-414f-b496-61266fbf1b55

操作步骤

**Comment by Azir-11** [comment]
测试了一下，没有复现出来，是啥设备的？在其他浏览器也会吗？

**Comment by Azir-11** [comment]
如果是这个浏览器所特有的bug的话，可能不会考虑修复，目前没有兼容全部移动端平台的计划，只能保证显示正常

**Comment by Chord-Labs** [comment]
用ipad上测试的， 所有浏览器都有这个bug

**Comment by honghuangdc** [comment]
我试了下，是存在这个问题
