### ISSUE TITLE
🐱‍🏍🐱‍🏍🐱‍🏍真诚邀请您使用alova

### ISSUE THREAD

**Issue by JOU-amjs** [soybeanjs/soybean-admin#625]
您好，我是alovajs的作者胡镇。

仔细看了您写的soybean-admin非常不错，界面也很耐看，然后我发现项目中使用的是axios，虽然做了一些请求层封装（@sa/axios），但使用方式还较为传统，所以尝试邀请您使用alova+axios，我们也会在alova官网推荐您的项目，不知道您有没兴趣，我简单介绍一下。

[alova文档](https://alova.js.org)

alova定位为下一代请求工具，它的场景化请求策略和更先进的openAPI方案，可以极致简化您项目的api调用，具体推荐您看下[alova简介](https://alova.js.org/tutorial/getting-started/introduce)，您的收益和成本大概是这样的：

收益：alova提供了15+个场景化的请求策略，以及响应缓存和请求共享等高级特性，后台管理多以列表和表单为主，alova的分页策略和表单提交策略都可以让你的项目使用者快速实现完整的列表和表单功能，配合openAPI还可以获得极致的API集成效率。
成本：我仔细看过soybean-admin源码，可以通过重写`@sa/axios`子包快速迁移，把创建的request函数内改成返回alova的method实例，调用那边与现在保持一致就可以，什么都不用动，因为alova的传参和axios保持了一致，然后也然后是100%适配axios的，你可以用到axios的所有功能。

这些应该会让您的项目增添一点色彩，要是有意向迁移的话，我会提供全力的支持，不知道您意下如何？可以随时通过微信号“alova_js”联系我哦！

**Comment by honghuangdc** [comment]
alova，确实挺不错的，考虑的场景也比较全，是个替换axios不错的选择。
目前 SoybeanAdmin 进入一个缓慢的维护阶段，要替换 axios 估计需要等到大版本的变更才可以。
为了做好兼容，可以后期再增加一个子包 @sa/alova

**Comment by JOU-amjs** [comment]
非常感谢认可，希望可以达成合作，需要我协助的时候随时联系我，直接回复此帖或加我微信都行。

对了，alova并不是要替换axios哦，而是增强了axios，让你的用户少写很多模板代码，享受开箱即用的高级请求特性，你可以同时使用alova+axios，就像rollup和vite关系那样。

**Comment by honghuangdc** [comment]
https://docs.soybeanjs.cn/zh/recommend/alova.html

**Comment by JOU-amjs** [comment]
😀感谢，我们先来提个PR
