### ISSUE TITLE
[Bug]: 控制台会提示 Sass 存在废弃的 API

### ISSUE THREAD

**Issue by m-xlsea** [soybeanjs/soybean-admin#627]
### 软件版本

1.3.6

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

    css: {
      preprocessorOptions: {
        scss: {
          additionalData: `@use "./src/styles/scss/global.scss" as *;`
        }
      }
    },
    
    可能是因为这段配置导致的

![image](https://github.com/user-attachments/assets/9d498e46-45a3-4f5f-92b6-700fb9ffca1a)

### 期望的结果是什么？

控制台不提示sass的警告提示

### 实际的结果是什么？

控制台存在sass的警告提示

### 日志记录（可选）

```golang
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api
```

**Comment by honghuangdc** [comment]
升级了sass，这个得上游vite去解决

**Comment by honghuangdc** [comment]
24e9e57
