### ISSUE TITLE
[功能]: 适用于前台风格的主题

### ISSUE THREAD

**Issue by remoteking** [soybeanjs/soybean-admin#631]
### 描述

我是后端，不会写前端，最近翻了几个前端项目，soybean支持自动路由，太棒了，然后可以看到完成度很高，细节，然后设计也很有特色，唯一遗憾的地方是有一个细分市场没有关注到，就是有一部分应用是介于前台和后台之间的。

### 建议的解决方案

本身是一个后台，但是要开放给客户使用，这需要一个类似于github登录以后那样的，或者比如qq邮箱那样的，头部是横向贯穿的，左边就正常菜单但不要竖向贯通。
如果有机会在项目中使用这个前端面板，我会给一份赞助。

**Comment by Azir-11** [comment]
像QQ邮箱那种左侧的菜单其实就是高度定制化的了，GitHub的也差不多，这种现在也可以做，使用顶部菜单模式，然后在页面内参考登录路由的做法，在页面内做一层菜单+路由的形式
至于通用性的话，因为现在的是后台，所以通用性还高一点，但如果换成前台了，各个企业的菜单设计肯定都有所差异，我们其实不太好做的，只能说最多就是提供一个示例

**Comment by remoteking** [comment]
以我们的官网为例，首页是前台风格，点指引就撕裂了，然后点常见问题会再撕回来，这实在是不太优雅对不对？

**Comment by Azir-11** [comment]
> 以我们的官网为例，首页是前台风格，点指引就撕裂了，然后点常见问题会再撕回来，这实在是不太优雅对不对？

没太懂是啥意思，我们的文档不是用soybean写的，用的是vitepress，常见问题和指引的差别是为了方便检索，可以说设计如此，不过这个和你的问题好像没什么太大关系吧

**Comment by remoteking** [comment]
我想表达的就是这个意思呢，当我们的后台系统需要与前台打通的时候，需要弱化后台，向前台融合，比如标签页一般用不到了，头部横向贯通保持一致的设计，左边菜单最多一级子菜单不要把客户吓到了，要兼容手机平板所以左上角的个人信息要换个地方展示。。

**Comment by remoteking** [comment]
不知道是不是错觉，我觉得咱这个项目确实做的很好，我最近试的几个要么感觉不美观，要么感觉不流畅，我们这个两方面都表现优秀。

**Comment by Azir-11** [comment]
> 我想表达的就是这个意思呢，当我们的后台系统需要与前台打通的时候，需要弱化后台，向前台融合，比如标签页一般用不到了，头部横向贯通保持一致的设计，左边菜单最多一级子菜单不要把客户吓到了，要兼容手机平板所以右上角的个人信息要换个地方展示。。

这些内容已经支持了

**Comment by Azir-11** [comment]
综上所述，我们应该不会考虑给项目增加适用于前台风格的主题，因为这是一个伪命题，你可以通过调整我们给出的众多配置项去调整成类似于自身前台的风格

**Comment by remoteking** [comment]
好吧我会试一下的。
