### ISSUE TITLE
[Bug]: 请求的token已过期，刷新token, 会退出登录

### ISSUE THREAD

**Issue by Chord-Labs** [soybeanjs/soybean-admin#632]
### 软件版本

1.3.7

### 运行环境

MacOS

### 运行架构

None

### 重现步骤

1. 触发 请求的token已过期，刷新token
2. 登出到登录页面

### 期望的结果是什么？

1. 正常刷新token

### 实际的结果是什么？

刷新token, 后登出到登录页面

**Comment by Azir-11** [comment]
两个请求返回的状态码分别是什么？
确认一下第一个接口返回的状态码是否为刷新token状态码
第二个接口返回的状态码是否为正常的成功状态码

**Comment by Chord-Labs** [comment]
soybeanjs.cn  同样有这个问题

**Comment by Chord-Labs** [comment]
是其他的问题，没问题了，

**Comment by Azir-11** [comment]
> soybeanjs.cn 同样有这个问题

示例里面是请求了一个特意会报错的接口，刷新token完毕后，再自动重新请求该接口，因为mock的token固定的原因，第二次的请求会失败并且返回登出，这里的逻辑是没有问题的
