### ISSUE TITLE
[Bug]: vue devtools无法正常工作

### ISSUE THREAD

**Issue by qiuquanwu** [soybeanjs/soybean-admin#634]
### 软件版本

1.3.7

### 运行环境

MacOS

### 运行架构

x86

### 重现步骤

运行之后，vue devtools无法正常使用，啥都不显示

### 期望的结果是什么？

vue devtools要能正常使用

### 实际的结果是什么？

运行之后，vue devtools无法正常使用，啥都不显示

**Comment by Azir-11** [comment]
未复现，可能是你没开
在项目启动之后，命令行会有提示，如：

  ➜  Local:   http://localhost:9527/
  ➜  Network: http://192.168.3.29:9527/
  ➜  Vue DevTools: Open http://localhost:9527/__devtools__/ as a separate window
  ➜  Vue DevTools: Press Option(⌥)+Shift(⇧)+D in App to toggle the Vue DevTools

这里最后一行的提示就是如何在页面激活devtools的，按一下快捷键试试
