### ISSUE TITLE
[Bug]: 菜单管理列表在数据多的时候不显示

### ISSUE THREAD

**Issue by xubaoguo** [soybeanjs/soybean-admin#635]
### 软件版本

最新版

### 运行环境

MacOS

### 运行架构

x86

### 重现步骤

[menu_data.txt](https://github.com/user-attachments/files/17145552/menu_data.txt)
附件是 json数据

### 期望的结果是什么？

正常显示列表

<img width="1069" alt="image" src="https://github.com/user-attachments/assets/2c68d9e0-ba3e-41b4-9606-2420f180b9b4">

### 实际的结果是什么？

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/6485ab5c-ac3c-43f7-a69d-b247e7d74a35">

### 日志记录（可选）

```golang
是
```

**Comment by Azir-11** [comment]
下午其他群友也遇到了类似的问题：

![62f75c83995a79f844782329233920aa](https://github.com/user-attachments/assets/9733753e-36b4-4b4d-a30f-8ff8139680d1)
根据这个需要的数据，通过后台进行返回了，然后前端做了以下改动
![e82fb1ec6124e1c6054288180cff1b6a](https://github.com/user-attachments/assets/e596fd4b-3117-444e-bcaa-e91d1d4df2d6)
![afd12e255ca0d7285b5a58d9296d8ff0](https://github.com/user-attachments/assets/a35793c4-086a-4123-ba2d-bf1e3702cc16)
然后目前界面报rowKey的错误
![066126d8ce253440d88a93011f561fae](https://github.com/user-attachments/assets/9a44317b-2ce8-47cd-883e-ec00b6d89bd2)

**Comment by honghuangdc** [comment]
字段 status 没有按照预期的类型返回结果，导致获取对应的 i18n key 得到的是undefined

**Comment by xubaoguo** [comment]
确实是 status 值异常导致的，感谢大佬
