### ISSUE TITLE
[Bug]: 菜单管理中，第二次点开新建菜单修改菜单类型时，页面组件v-if的控制showPage没有变化

### ISSUE THREAD

**Issue by ddpmz** [soybeanjs/soybean-admin#638]
### 软件版本

example 分支

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

拉取最新example分支代码 运行
进入菜单管理，第一次点击新增按钮，切换菜单类型时，页面组件选择框会正常切换显示隐藏；
关闭新增窗口，第二次点击新增按钮，切换菜单类型，页面组件选择框不会切换显示隐藏。

### 期望的结果是什么？

showPage 值根据 model.menuType 发生变化

### 实际的结果是什么？

showPage 值没有根据 model.menuType 发生变化

**Comment by Azir-11** [comment]
已修复
