### ISSUE TITLE
[Bug]: can not run the project with vscode  

### ISSUE THREAD

**Issue by honghh2018** [soybeanjs/soybean-admin#645]
### 软件版本

18.15.0

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

git clone https://github.com/soybeanjs/soybean-admin.git
into vscode open the soybean-admin
pnpm -i 
(base) PS D:\project\nodeproject\test_backend\d20241017\soybean-admin> pnpm -i
 ERROR  Unknown option: 'interactive'

### 期望的结果是什么？

hope to solve this issue

### 实际的结果是什么？

(base) PS D:\project\nodeproject\test_backend\d20241017\soybean-admin> pnpm -i
 ERROR  Unknown option: 'interactive'

**Comment by Azir-11** [comment]
是pnpm i而不是pnpm -i，pnpm没有-i这种命令

**Comment by honghh2018** [comment]
您好！已经收到邮件，祝好！                                    洪汉辉

**Comment by honghh2018** [comment]
好的，linux用习惯了
