### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dreamsnail** [soybeanjs/soybean-admin#648]
### 软件版本

v1.3.6

### 运行环境

MacOS

### 运行架构

None

### 重现步骤

function handleInitModel() {
  Object.assign(model, createDefaultModel());

  if (props.operateType === 'edit' && props.rowData) {
    Object.assign(model, props.rowData);
  }
}
这个初始化的方法，如果编辑后model中存了id，createTime，关闭对话框后在新建，id和createTime并没有被覆盖掉

### 期望的结果是什么？

每次关闭对话框，model值会被清空

### 实际的结果是什么？

model为及时清空

**Comment by Azir-11** [comment]
参考这个写法，把响应式的reactive换成ref
```
function handleInitModel() {
  if (props.operateType === 'add') {
    model.value = createDefaultModel();
    return;
  }

  if (!props.rowData) {
    return;
  }

  model.value = props.rowData;
}
```
