### ISSUE TITLE
ERR_PNPM_TARBALL_EXTRACT  Failed to add tarball from "https://registry.npmmirror.com/@iconify/json/-/json-2.2.258.tgz" to store: Array buffer allocation failed

### ISSUE THREAD

**Issue by 2595231928** [soybeanjs/soybean-admin#651]
PS D:\WorkSpace\soybean-admin-main> pnpm i
Scope: all 10 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +876
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading @iconify/json@2.2.258: 74.96 MB/74.96 MB, done
 WARN  GET https://registry.npmmirror.com/@iconify/json/-/json-2.2.258.tgz error (ERR_PNPM_TARBALL_EXTRACT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/@iconify/json/-/json-2.2.258.tgz error (ERR_PNPM_TARBALL_EXTRACT). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_TARBALL_EXTRACT  Failed to add tarball from "https://registry.npmmirror.com/@iconify/json/-/json-2.2.258.tgz" to store: Array buffer allocation failed
Progress: resolved 876, reused 747, downloaded 128, added 875
RegisterWaitForSingleObject: (8) 内存资源不足，无法处理此命令。

**Comment by Azir-11** [comment]
1. 确认磁盘空间是否充足
2. 确认内存是否充足
3. 更换镜像源
4. 关闭杀毒软件

**Comment by 2595231928** [comment]
> 1. 确认磁盘空间是否充足
> 2. 确认内存是否充足
> 3. 更换镜像源
> 4. 关闭杀毒软件

1，2 充足
3 换过镜像 但是还是失败
4 这个我再试试

**Comment by 2595231928** [comment]
> 1. 确认磁盘空间是否充足
> 2. 确认内存是否充足
> 3. 更换镜像源
> 4. 关闭杀毒软件

https://registry.npmmirror.com/@iconify/json/-/json-2.2.258.tgz  
这个包用浏览器也能下载下来
