### ISSUE TITLE
[Bug]: 中文文档常见问题板块关于反向代理的解释与正向代理一致的错误

### ISSUE THREAD

**Issue by PMAT77** [soybeanjs/soybean-admin#653]
### 软件版本

无

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

![Snipaste_2024-10-24_12-36-53](https://github.com/user-attachments/assets/33840ff3-24ee-4137-9cc0-b7d48fdcd3f5)

### 期望的结果是什么？

正向代理
正向代理即是客户端代理, 代理客户端, 服务端不知道实际发起请求的客户.

反向代理
<s>正向代理即是客户端代理, 代理客户端, 服务端不知道实际发起请求的客户端.<s>

### 实际的结果是什么？

中文文档常见问题板块关于反向代理的解释与正向代理一致

**Comment by honghuangdc** [comment]
在代码库 soybean-admin-doc 提个issue

**Comment by Azir-11** [comment]
感谢反馈，已修复
