### ISSUE TITLE
[功能]: 系统更新自动检测能力增强

### ISSUE THREAD

**Issue by NHZEX** [soybeanjs/soybean-admin#657]
### 描述

- 目前只有`visibilitychange`事件作为触发器，建议增加一个轮询定时器间隔主动触发检测。

比如用户长时间前台空置页面后又继续使用，导致触发不了这个事件。更新提示无法及时提醒概率增大。

1. 存在资源文件更新后用户继续操作引发卡死白屏情况（目前服务端更新时是整体替换不保留老文件，如果继续使用老版本前端会导致没有执行过的功能代码后续没加载）。
2. 问题修复后用户可能因为各种情况没收到通知，依然会继续反馈老问题。

- 建议支持从 GET 请求改为使用 HEAD 请求

使用标准请求头`etag`来作为更新的判断依据（正确配置的服务器都应该稳定提供该值的），节省服务器下行传输消耗的流量。

### 建议的解决方案

增强的方案实现：[app-version-check.ts](https://github.com/NHZEX/nxAdmin-soybean-admin/blob/dev/4.x/src/plugins/app-version-check.ts)

**Comment by Azir-11** [comment]
你这个写的稍微有点问题，我没参考你的直接按着功能重新写了一些🤣🤣🤣
