### ISSUE TITLE
[功能]: 封装的table没考虑过服务端返回的数据结构不统一吗？

### ISSUE THREAD

**Issue by ghost** [soybeanjs/soybean-admin#659]
### 描述

如果data里面直接就是数据呢，不存在records怎么办，或者返回的数据需要处理呢？

### 建议的解决方案

如果data里面直接就是数据呢，不存在records怎么办，或者返回的数据需要处理呢？

**Comment by Azir-11** [comment]
这是js基础的内容，不存在records就直接取值啊，整个res就是你的data，至于page、size、total等这些内容你就自己算出来就好了，代码放出来是可以改的，不是刻在石板上不能变的。

**Comment by 1312003804** [comment]
是能去判断，然后处理 那封装的意义在哪呢

**Comment by Azir-11** [comment]
我们为全部人服务，不是为你服务，你的场景独特而已

**Comment by Azir-11** [comment]
而且文档写的很清楚，也强调过几次了，useTable只是一个我们认为的较为通用的白板实现，如果你的需求较为特殊，可以根据文档提供的配置项自行实现一个或是多个 useTable 函数。

**Comment by honghuangdc** [comment]
说白了就是，内心：我不想写代码，你为啥不能封装好，考虑所有的场景

我的评价是，你不适合

**Comment by RongleCat** [comment]
明显是你们后端的问题，没有按照框架的数据结构返回数据，建议和后端掰头

**Comment by pixelmaxQm** [comment]
![b2eda444cc07e7fddda1cbaba15827f](https://github.com/user-attachments/assets/c37e44bf-9c78-4789-aa8e-255806e9791f)

不如花钱定制一下呢

**Comment by 1312003804** [comment]
6,如果就有一个列表需要处理，我是用呢还是不用呢，用要不就加if 要不就复制一个 舔狗就舔吧

**Comment by honghuangdc** [comment]
要不你自己封装一个吧，相信你自己，封不出来就不睡觉

**Comment by majinkai** [comment]
data就是数据的话，那肯定只是一个列表，不需要分页，也不需要useTable了

**Comment by Azir-11** [comment]
> 6,如果就有一个列表需要处理，我是用呢还是不用呢，用要不就加if 要不就复制一个 舔狗就舔吧

给你脸了臭傻逼？你他妈没手还是怎么样？request的api那里不能处理？transformer不能往外提？在家里饭来张口衣来伸手习惯了？没有你爹给你写代码就不会用了？操你妈的有本事就别用，自己写去，真是给你脸了

**Comment by shufuya** [comment]
不是，你的脑子只有核桃大小吗，处理数据都不会？还要人家封装好给你，你自己不会改源码？哪里来的臭傻逼

**Comment by Azir-11** [comment]
继续叫，我给你open了

**Comment by xue-ding-e** [comment]
![e376aba2226e93c19642373a1511b28](https://github.com/user-attachments/assets/15acb37e-a683-4721-bff3-ddd481c2542e)

**Comment by ydcloud-dy** [comment]
不是，就处理个数据都懒得弄？饭给你做好了还得喂到你嘴里？

**Comment by NanCrane** [comment]
少爷还没有断奶，还是没吃过饭，得需要人来喂到您嘴里面

**Comment by xiaoyu-zl** [comment]
我觉得是培训班的问题没把你教好就放出来，让培训班退你钱

**Comment by honghuangdc** [comment]
对接微信sdk时，你发现后端给你的字段和微信的sdk字段不一致，你做好赶紧去呼叫马化腾，让他帮你整改微信sdk。

**Comment by iceskyfrost** [comment]
黑马的,还是尚硅谷的?

**Comment by pixelmaxQm** [comment]
> 黑马的,还是尚硅谷的?

${北大}_{青鸟}$的

**Comment by Tiamo-web66** [comment]
降低语气，正常交流，有可以优化的地方，合理的意见可以提，不要把别人无私奉献当成理所应当，上来就是爷爷口气，谁惯着你，挨骂只能说是活该。

**Comment by pixelmaxQm** [comment]
你们这些坏人，给人家乐子人骂销号了。
