### ISSUE TITLE
有个问题大佬们

### ISSUE THREAD

**Issue by Sky-XQ** [soybeanjs/soybean-admin#660]
const columns: DataTableColumns = [
  {
    type: 'selection',
    align: 'center',
    width: 48
  },
  {
    key: 'typeName',
    title: $t('page.sheetMusicType.sheetMusicTypeTable.name'),
    align: 'center',
    width: 300
  },
  {
    key: 'id',
    title: $t('page.sheetMusicType.sheetMusicTypeTable.id'),
    align: 'center',
    minWidth: 120
  },
  {
    key: 'parentId',
    title: $t('page.sheetMusicType.sheetMusicTypeTable.parentId'),
    align: 'center',
    minWidth: 120
  },
  {
    key: 'parentName',
    title: $t('page.sheetMusicType.sheetMusicTypeTable.parentName'),
    align: 'center',
    minWidth: 120,
    render(row) {
      let value = '-';
      if (row.parentName) {
        value = row.parentName;
      }
      return value;
    }
  }
];
![image](https://github.com/user-attachments/assets/7f890f17-0018-4305-8910-b98e1961bd32) 这是什么原因

**Comment by Azir-11** [comment]
你编译器认为这个row. parentName是一个空对象，检查一下apiFn的返回类型里这个parentName的类型定义是否准确

**Comment by Sky-XQ** [comment]
数据是没问题的，我不清楚是哪块错了 因为一直弄vue2了 刚开始研究vue3 我加了个value = String(row.parentName);  是不报错了 但是不知道这样写好吗 哈哈

**Comment by Azir-11** [comment]
这个报错是类型问题，不是数据问题，是ts认为你的类型不对导致的，如果类型声明的是string还报这个错就可能是ts校验有误，可能尝试重启ts serve，ts报错和实际运行无关，用String包裹之后他的类型就强制变成了string，那赋值给string类型的value自然就不会有问题了

**Comment by Sky-XQ** [comment]
好的 谢谢大佬，我还有疑问就是ts不是得定义类型嘛，是不是也可以理解为把服务端的类型也给定义了 哈哈 是这个意思吗 因为每个api的返回都需要定义 总不能都是any

**Comment by Sky-XQ** [comment]
好的 理解了 谢谢
