### ISSUE TITLE
[功能]: 请教

### ISSUE THREAD

**Issue by quhongli123** [soybeanjs/soybean-admin#662]
### 描述

如何关闭自动生成路由

### 建议的解决方案

no

**Comment by Azir-11** [comment]
？

**Comment by Azir-11** [comment]
你确定要手动维护路由文件？

**Comment by quhongli123** [comment]
> 你确定要手动维护路由文件？

是的 不想通过启动根据目录生成路由[捂脸]

**Comment by Azir-11** [comment]
为什么呢

**Comment by quhongli123** [comment]
太约定了

**Comment by Azir-11** [comment]
不想要这个约定，你需要完整的移除路由相关内容，并自己实现一个你想要的效果，单关闭生成没用

**Comment by quhongli123** [comment]
比如   项目列表/任务列表/任务详情 像这种路由结构 有案例吗

**Comment by honghuangdc** [comment]
你这样理解，业务上的上下级关系不要带到文件的上下级关系中

**Comment by honghuangdc** [comment]
比如 业务上 项目列表 => 任务列表 => 任务详情 有这样的上下级的关系
从页面布局的角度去看，都是同一个布局和单独页面

- project
   - list
   - task
   - task-detail

**Comment by honghuangdc** [comment]
创建这样的文件结构就行

**Comment by quhongli123** [comment]
这种的话需要对面包屑上处理下？ 面包屑并不会项目列表 => 任务列表 => 任务详情 这种结构展示

**Comment by Azir-11** [comment]
目前面包屑是不会这么显示的，面包屑当前反应的是文件夹结构的信息，相关内容还在考虑怎么设计，目前只能这样了
