### ISSUE TITLE
[Bug]: example 分支，无法启动 pnpm run dev

### ISSUE THREAD

**Issue by Iixuanzheng** [soybeanjs/soybean-admin#664]
### 软件版本

examplle

### 运行环境

MacOS

### 运行架构

AMD64

### 重现步骤

![CleanShot 2024-11-11 at 10 54 58@2x](https://github.com/user-attachments/assets/7591ed81-ec14-40bd-9d6d-72c8980743d6)

### 期望的结果是什么？

OK

### 实际的结果是什么？

![CleanShot 2024-11-11 at 10 54 58@2x](https://github.com/user-attachments/assets/56739d4f-a91a-4be8-8566-376276ce8c78)

**Comment by honghuangdc** [comment]
```bash
pnpm update-pkg
pnpm cleanup
pnpm i
```
