### ISSUE TITLE
[Feature]:是不是不支持自定义content-type

### ISSUE THREAD

**Issue by fish-kings** [soybeanjs/soybean-admin#673]
### Description

自定义contenttype 无法生效
![image](https://github.com/user-attachments/assets/6dce1289-5882-4e4c-b9a3-8e20b5ca4533)

### Suggested Solution

应该支持自定义contenttype

**Comment by kiss-keray** [comment]
为什么关闭了？应该怎么设置？

**Comment by Azir-11** [comment]
> 为什么关闭了？应该怎么设置？

就像他图里这样设置

**Comment by kiss-keray** [comment]
> > 为什么关闭了？应该怎么设置？
> 
> 就像他图里这样设置

![Image](https://github.com/user-attachments/assets/20ffd5ca-8281-4178-b5f2-73352f704713)

![Image](https://github.com/user-attachments/assets/bf3425f6-084e-4003-be18-dca22390961b)

![Image](https://github.com/user-attachments/assets/02c6afa4-86a1-4918-bd8c-5be38f0546cc)

![Image](https://github.com/user-attachments/assets/fe75c2b9-a7d4-4012-8fde-275db562f7e7)


输出都没问题，但是在实际请求时Content-type没有了

**Comment by kiss-keray** [comment]
> > 为什么关闭了？应该怎么设置？
> 
> 就像他图里这样设置

找到问题了 post参数放data没改写到params了
