### ISSUE TITLE
[Bug]: 内网环境网络不通

### ISSUE THREAD

**Issue by bleedyao** [soybeanjs/soybean-admin#678]
### 软件版本

1.3.8

### 运行环境

MacOS

### 运行架构

None

### 重现步骤

我这里是一个内网环境，访问外网需要配置网络代理。

测试 1：

在纯外网环境下，项目可以成功登录。而切到内网环境，就会出现 10 秒超时，无法登录。

已经尝试在终端中设置 http_proxy 和 https_proxy 仍不起作用。

测试 2：

将 VITE_HTTP_PROXY 设置成 N，关闭代理。登录时直接访问 mock 地址，可以成功登录，但之后再请求内网链接会出现跨域访问的错误。

此时开启代理（VITE_HTTP_PROXY=Y），内网网址可以访问，但很快会推出至登录界面。继续登录依然失败。

### 期望的结果是什么？

项目在内网环境中可以正常登录和访问内网链接

### 实际的结果是什么？

开启代理时，显示登录超时。

关闭代理时，可以成功登录，但访问链接会出现跨域访问错误。

**Comment by honghuangdc** [comment]
内网环境的问题自行解决，和外网的没啥区别，后端该配置代理的配置代理
后端请求要用自己的服务那就用，别用项目mock的服务，又用内网的
