### ISSUE TITLE
[Bug]: 关于静态路由下，页面刷新后会访问不到authStore导致权限路由不能访问

### ISSUE THREAD

**Issue by jcjrobert** [soybeanjs/soybean-admin#681]
### 软件版本

1.3.9

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

路由设置为静态路由，首次登录后权限路由正常显示，但刷新后权限路由会消失，经排查是因为创建路由守卫时访问authStore是空的，但是调用getUserInfo访问的authStore数据正常
本人是前端苦手，虽然已解决但是很粗糙，在路由守卫创建前完善authStore
```js
/** Setup Vue Router */
export async function setupRouter(app: App) {
  const authStore = useAuthStore();
  const { data: info, error } = await authStore.fetchGetUserInfo();
  if (!error) Object.assign(authStore.userInfo, info);
  app.use(router);
  createRouterGuard(router);
  await router.isReady();
}
```
这样注销会出问题，所以我还改了一下注销
```js
if (!route || !route.meta || !route.meta.constant) {
      await toLogin();
    }
```

### 期望的结果是什么？

权限路由正常显示

### 实际的结果是什么？

权限路由丢失

**Comment by honghuangdc** [comment]
https://github.com/soybeanjs/soybean-admin/commit/ba38119efd31252ad4fd5d061896572735f4b57b

**Comment by jcjrobert** [comment]
> [ba38119](https://github.com/soybeanjs/soybean-admin/commit/ba38119efd31252ad4fd5d061896572735f4b57b)
> 
> 刚修复了，再试试

可以了，感谢及时修复
