### ISSUE TITLE
[功能]: monorepo模式下，packages里的依赖如何发包

### ISSUE THREAD

**Issue by AzronChan** [soybeanjs/soybean-admin#684]
### 描述

packages 里的依赖包如果能共享给其他项目更好；

### 建议的解决方案

对packages里的依赖包增加命名以及vite配置，独立发包

**Comment by honghuangdc** [comment]
可以使用 `tsup`或者 `unbuild` 对packages里面的包进行打包，然后更改一下`package.json`的`exports`, 其中使用`unbuild`时可以借助`stub`命令使本地开发时直接使用TS源代码
