### ISSUE TITLE
[功能]: 希望能支持嵌套路由

### ISSUE THREAD

**Issue by BowieY** [soybeanjs/soybean-admin#686]
### 描述

无法实现嵌套路由：在多级路由的场景下，仅能显示末端路由组件（即不包含children属性）。任何只要包含了children属性的路由始终被认为是菜单。

### 建议的解决方案

希望可以在meta或其他地方增加一个属性来标识包含了children属性的路由组件是页面还是菜单。

**Comment by honghuangdc** [comment]
在插件的[仓库ElegantRouter](https://github.com/soybeanjs/elegant-router)这里提一下issues 
目前的路由插件有一些限制，后续会重构新版本，将不会有层级的限制，菜单数据和路由数据分离，就没有嵌套的限制了

**Comment by BowieY** [comment]
好的，谢谢。
